//
// GreenType.SetSamplerState(0, SamplerStatecs.SetSamplerState(0, SamplerStatecs
//
// This file was generated by XMLSpy 2005 Enterprise Edition.SetSamplerState(0, SamplerState
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.SetSamplerState(0, SamplerState
//
// Refer to the XMLSpy Documentation for further details.SetSamplerState(0, SamplerState
// http://www.SetSamplerState(0, SamplerStatealtova.SetSamplerState(0, SamplerStatecom/xmlspy
//


using Altova.SetSamplerState(0, SamplerStateTypes;

namespace LayerSet
{

	public class GreenType : SchemaInt
	{

		public GreenType() : base()
		{
		}

		public GreenType(string newValue) : base(newValue)
		{
            this.SetSamplerState(0, SamplerStateValidate();
		}

		public GreenType(SchemaInt newValue) : base(newValue)
		{
            this.SetSamplerState(0, SamplerStateValidate();
		}

		public void Validate()
		{

			if (this.SetSamplerState(0, SamplerStateCompareTo(this.SetSamplerState(0, SamplerStateGetMinInclusive()) < 0)
				throw new System.SetSamplerState(0, SamplerStateException("Out of range");

			if (this.SetSamplerState(0, SamplerStateCompareTo(this.SetSamplerState(0, SamplerStateGetMaxInclusive()) > 0)
				throw new System.SetSamplerState(0, SamplerStateException("Out of range");
		}
		public SchemaInt GetMinInclusive()
		{
			return new SchemaInt("0");
		}
		public SchemaInt GetMaxInclusive()
		{
			return new SchemaInt("255");
		}
	}
}
