//
// MeshFilePathType2.SetSamplerState(0, SamplerStatecs.SetSamplerState(0, SamplerStatecs
//
// This file was generated by XMLSpy 2005 Enterprise Edition.SetSamplerState(0, SamplerState
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.SetSamplerState(0, SamplerState
//
// Refer to the XMLSpy Documentation for further details.SetSamplerState(0, SamplerState
// http://www.SetSamplerState(0, SamplerStatealtova.SetSamplerState(0, SamplerStatecom/xmlspy
//


using Altova.SetSamplerState(0, SamplerStateTypes;

namespace LayerSet
{

	public class MeshFilePathType2 : SchemaString
	{

		public MeshFilePathType2() : base()
		{
		}

		public MeshFilePathType2(string newValue) : base(newValue)
		{
            this.SetSamplerState(0, SamplerStateValidate();
		}

		public MeshFilePathType2(SchemaString newValue) : base(newValue)
		{
            this.SetSamplerState(0, SamplerStateValidate();
		}

		public void Validate()
		{
			if (this.SetSamplerState(0, SamplerStateValue.SetSamplerState(0, SamplerStateLength < this.SetSamplerState(0, SamplerStateGetMinLength())
				throw new System.SetSamplerState(0, SamplerStateException("Too short");
		}
		public int GetMinLength()
		{
			return 1;
		}
	}
}
