//
// Type_ShapeFileLayer.cs.cs
//
// This file was generated by XMLSpy 2005 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;
using System.Collections;
using System.Xml;
using Altova.Types;

namespace LayerSet
{
	public class Type_ShapeFileLayer : Altova.Xml.Node
	{
		#region Forward constructors
		public Type_ShapeFileLayer() : base() {
            this.SetCollectionParents(); }
		public Type_ShapeFileLayer(XmlDocument doc) : base(doc) {
            this.SetCollectionParents(); }
		public Type_ShapeFileLayer(XmlNode node) : base(node) {
            this.SetCollectionParents(); }
		public Type_ShapeFileLayer(Altova.Xml.Node node) : base(node) {
            this.SetCollectionParents(); }
		#endregion // Forward constructors

		public override void AdjustPrefix()
		{

			for (int i = 0; i < this.DomChildCount(NodeType.Attribute, "", "ShowAtStartup"); i++)
			{
				XmlNode DOMNode = this.GetDomChildAt(NodeType.Attribute, "", "ShowAtStartup", i);
				InternalAdjustPrefix(DOMNode, false);
			}

			for (int i = 0; i < this.DomChildCount(NodeType.Element, "", "Name"); i++)
			{
				XmlNode DOMNode = this.GetDomChildAt(NodeType.Element, "", "Name", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < this.DomChildCount(NodeType.Element, "", "DistanceAboveSurface"); i++)
			{
				XmlNode DOMNode = this.GetDomChildAt(NodeType.Element, "", "DistanceAboveSurface", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < this.DomChildCount(NodeType.Element, "", "MasterFilePath"); i++)
			{
				XmlNode DOMNode = this.GetDomChildAt(NodeType.Element, "", "MasterFilePath", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < this.DomChildCount(NodeType.Element, "", "MinimumViewAltitude"); i++)
			{
				XmlNode DOMNode = this.GetDomChildAt(NodeType.Element, "", "MinimumViewAltitude", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < this.DomChildCount(NodeType.Element, "", "MaximumViewAltitude"); i++)
			{
				XmlNode DOMNode = this.GetDomChildAt(NodeType.Element, "", "MaximumViewAltitude", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < this.DomChildCount(NodeType.Element, "", "ShowPoints"); i++)
			{
				XmlNode DOMNode = this.GetDomChildAt(NodeType.Element, "", "ShowPoints", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < this.DomChildCount(NodeType.Element, "", "ShowBoundaries"); i++)
			{
				XmlNode DOMNode = this.GetDomChildAt(NodeType.Element, "", "ShowBoundaries", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < this.DomChildCount(NodeType.Element, "", "ShowFilledRegions"); i++)
			{
				XmlNode DOMNode = this.GetDomChildAt(NodeType.Element, "", "ShowFilledRegions", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < this.DomChildCount(NodeType.Element, "", "ScalarKey"); i++)
			{
				XmlNode DOMNode = this.GetDomChildAt(NodeType.Element, "", "ScalarKey", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < this.DomChildCount(NodeType.Element, "", "ShowScalarValues"); i++)
			{
				XmlNode DOMNode = this.GetDomChildAt(NodeType.Element, "", "ShowScalarValues", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < this.DomChildCount(NodeType.Element, "", "DisplayFont"); i++)
			{
				XmlNode DOMNode = this.GetDomChildAt(NodeType.Element, "", "DisplayFont", i);
				InternalAdjustPrefix(DOMNode, true);
				new Type_DisplayFont2(DOMNode).AdjustPrefix();
			}

			for (int i = 0; i < this.DomChildCount(NodeType.Element, "", "RGBColor"); i++)
			{
				XmlNode DOMNode = this.GetDomChildAt(NodeType.Element, "", "RGBColor", i);
				InternalAdjustPrefix(DOMNode, true);
				new Type_RGBColor2(DOMNode).AdjustPrefix();
			}

			for (int i = 0; i < this.DomChildCount(NodeType.Element, "", "WinColorName"); i++)
			{
				XmlNode DOMNode = this.GetDomChildAt(NodeType.Element, "", "WinColorName", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < this.DomChildCount(NodeType.Element, "", "ExtendedInformation"); i++)
			{
				XmlNode DOMNode = this.GetDomChildAt(NodeType.Element, "", "ExtendedInformation", i);
				InternalAdjustPrefix(DOMNode, true);
				new Type_ExtendedInformation(DOMNode).AdjustPrefix();
			}
		}


		#region ShowAtStartup accessor methods
		public int GetShowAtStartupMinCount()
		{
			return 1;
		}

		public int ShowAtStartupMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetShowAtStartupMaxCount()
		{
			return 1;
		}

		public int ShowAtStartupMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetShowAtStartupCount()
		{
			return this.DomChildCount(NodeType.Attribute, "", "ShowAtStartup");
		}

		public int ShowAtStartupCount
		{
			get
			{
				return this.DomChildCount(NodeType.Attribute, "", "ShowAtStartup");
			}
		}

		public bool HasShowAtStartup()
		{
			return this.HasDomChild(NodeType.Attribute, "", "ShowAtStartup");
		}

		public SchemaBoolean GetShowAtStartupAt(int index)
		{
			return new SchemaBoolean(GetDomNodeValue(this.GetDomChildAt(NodeType.Attribute, "", "ShowAtStartup", index)));
		}

		public XmlNode GetStartingShowAtStartupCursor()
		{
			return this.GetDomFirstChild( NodeType.Attribute, "", "ShowAtStartup" );
		}

		public XmlNode GetAdvancedShowAtStartupCursor( XmlNode curNode )
		{
			return this.GetDomNextChild( NodeType.Attribute, "", "ShowAtStartup", curNode );
		}

		public SchemaBoolean GetShowAtStartupValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaBoolean( curNode.Value );
		}


		public SchemaBoolean GetShowAtStartup()
		{
			return this.GetShowAtStartupAt(0);
		}

		public SchemaBoolean ShowAtStartup
		{
			get
			{
				return this.GetShowAtStartupAt(0);
			}
		}

		public void RemoveShowAtStartupAt(int index)
		{
            this.RemoveDomChildAt(NodeType.Attribute, "", "ShowAtStartup", index);
		}

		public void RemoveShowAtStartup()
		{
			while (this.HasShowAtStartup()) this.RemoveShowAtStartupAt(0);
		}

		public void AddShowAtStartup(SchemaBoolean newValue)
		{
            this.AppendDomChild(NodeType.Attribute, "", "ShowAtStartup", newValue.ToString());
		}

		public void InsertShowAtStartupAt(SchemaBoolean newValue, int index)
		{
            this.InsertDomChildAt(NodeType.Attribute, "", "ShowAtStartup", index, newValue.ToString());
		}

		public void ReplaceShowAtStartupAt(SchemaBoolean newValue, int index)
		{
            this.ReplaceDomChildAt(NodeType.Attribute, "", "ShowAtStartup", index, newValue.ToString());
		}
		#endregion // ShowAtStartup accessor methods

		#region ShowAtStartup collection
        public ShowAtStartupCollection	MyShowAtStartups = new ShowAtStartupCollection( );

        public class ShowAtStartupCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
                    this.parent = value;
				}
			}
			public ShowAtStartupEnumerator GetEnumerator() 
			{
				return new ShowAtStartupEnumerator(this.parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return this.GetEnumerator();
			}
        }

        public class ShowAtStartupEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public ShowAtStartupEnumerator(Type_ShapeFileLayer par) 
			{
                this.parent = par;
                this.nIndex = -1;
			}
			public void Reset() 
			{
                this.nIndex = -1;
			}
			public bool MoveNext() 
			{
                this.nIndex++;
				return(this.nIndex < this.parent.ShowAtStartupCount );
			}
			public SchemaBoolean  Current 
			{
				get 
				{
					return(this.parent.GetShowAtStartupAt(this.nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(this.Current);
				}
			}
    	}

        #endregion // ShowAtStartup collection

		#region Name accessor methods
		public int GetNameMinCount()
		{
			return 1;
		}

		public int NameMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetNameMaxCount()
		{
			return 1;
		}

		public int NameMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetNameCount()
		{
			return this.DomChildCount(NodeType.Element, "", "Name");
		}

		public int NameCount
		{
			get
			{
				return this.DomChildCount(NodeType.Element, "", "Name");
			}
		}

		public bool HasName()
		{
			return this.HasDomChild(NodeType.Element, "", "Name");
		}

		public SchemaString GetNameAt(int index)
		{
			return new SchemaString(GetDomNodeValue(this.GetDomChildAt(NodeType.Element, "", "Name", index)));
		}

		public XmlNode GetStartingNameCursor()
		{
			return this.GetDomFirstChild( NodeType.Element, "", "Name" );
		}

		public XmlNode GetAdvancedNameCursor( XmlNode curNode )
		{
			return this.GetDomNextChild( NodeType.Element, "", "Name", curNode );
		}

		public SchemaString GetNameValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaString( curNode.InnerText );
		}


		public SchemaString GetName()
		{
			return this.GetNameAt(0);
		}

		public SchemaString Name
		{
			get
			{
				return this.GetNameAt(0);
			}
		}

		public void RemoveNameAt(int index)
		{
            this.RemoveDomChildAt(NodeType.Element, "", "Name", index);
		}

		public void RemoveName()
		{
			while (this.HasName()) this.RemoveNameAt(0);
		}

		public void AddName(SchemaString newValue)
		{
            this.AppendDomChild(NodeType.Element, "", "Name", newValue.ToString());
		}

		public void InsertNameAt(SchemaString newValue, int index)
		{
            this.InsertDomChildAt(NodeType.Element, "", "Name", index, newValue.ToString());
		}

		public void ReplaceNameAt(SchemaString newValue, int index)
		{
            this.ReplaceDomChildAt(NodeType.Element, "", "Name", index, newValue.ToString());
		}
		#endregion // Name accessor methods

		#region Name collection
        public NameCollection	MyNames = new NameCollection( );

        public class NameCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
                    this.parent = value;
				}
			}
			public NameEnumerator GetEnumerator() 
			{
				return new NameEnumerator(this.parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return this.GetEnumerator();
			}
        }

        public class NameEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public NameEnumerator(Type_ShapeFileLayer par) 
			{
                this.parent = par;
                this.nIndex = -1;
			}
			public void Reset() 
			{
                this.nIndex = -1;
			}
			public bool MoveNext() 
			{
                this.nIndex++;
				return(this.nIndex < this.parent.NameCount );
			}
			public SchemaString  Current 
			{
				get 
				{
					return(this.parent.GetNameAt(this.nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(this.Current);
				}
			}
    	}

        #endregion // Name collection

		#region DistanceAboveSurface accessor methods
		public int GetDistanceAboveSurfaceMinCount()
		{
			return 1;
		}

		public int DistanceAboveSurfaceMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetDistanceAboveSurfaceMaxCount()
		{
			return 1;
		}

		public int DistanceAboveSurfaceMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetDistanceAboveSurfaceCount()
		{
			return this.DomChildCount(NodeType.Element, "", "DistanceAboveSurface");
		}

		public int DistanceAboveSurfaceCount
		{
			get
			{
				return this.DomChildCount(NodeType.Element, "", "DistanceAboveSurface");
			}
		}

		public bool HasDistanceAboveSurface()
		{
			return this.HasDomChild(NodeType.Element, "", "DistanceAboveSurface");
		}

		public SchemaDecimal GetDistanceAboveSurfaceAt(int index)
		{
			return new SchemaDecimal(GetDomNodeValue(this.GetDomChildAt(NodeType.Element, "", "DistanceAboveSurface", index)));
		}

		public XmlNode GetStartingDistanceAboveSurfaceCursor()
		{
			return this.GetDomFirstChild( NodeType.Element, "", "DistanceAboveSurface" );
		}

		public XmlNode GetAdvancedDistanceAboveSurfaceCursor( XmlNode curNode )
		{
			return this.GetDomNextChild( NodeType.Element, "", "DistanceAboveSurface", curNode );
		}

		public SchemaDecimal GetDistanceAboveSurfaceValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaDecimal( curNode.InnerText );
		}


		public SchemaDecimal GetDistanceAboveSurface()
		{
			return this.GetDistanceAboveSurfaceAt(0);
		}

		public SchemaDecimal DistanceAboveSurface
		{
			get
			{
				return this.GetDistanceAboveSurfaceAt(0);
			}
		}

		public void RemoveDistanceAboveSurfaceAt(int index)
		{
            this.RemoveDomChildAt(NodeType.Element, "", "DistanceAboveSurface", index);
		}

		public void RemoveDistanceAboveSurface()
		{
			while (this.HasDistanceAboveSurface()) this.RemoveDistanceAboveSurfaceAt(0);
		}

		public void AddDistanceAboveSurface(SchemaDecimal newValue)
		{
            this.AppendDomChild(NodeType.Element, "", "DistanceAboveSurface", newValue.ToString());
		}

		public void InsertDistanceAboveSurfaceAt(SchemaDecimal newValue, int index)
		{
            this.InsertDomChildAt(NodeType.Element, "", "DistanceAboveSurface", index, newValue.ToString());
		}

		public void ReplaceDistanceAboveSurfaceAt(SchemaDecimal newValue, int index)
		{
            this.ReplaceDomChildAt(NodeType.Element, "", "DistanceAboveSurface", index, newValue.ToString());
		}
		#endregion // DistanceAboveSurface accessor methods

		#region DistanceAboveSurface collection
        public DistanceAboveSurfaceCollection	MyDistanceAboveSurfaces = new DistanceAboveSurfaceCollection( );

        public class DistanceAboveSurfaceCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
                    this.parent = value;
				}
			}
			public DistanceAboveSurfaceEnumerator GetEnumerator() 
			{
				return new DistanceAboveSurfaceEnumerator(this.parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return this.GetEnumerator();
			}
        }

        public class DistanceAboveSurfaceEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public DistanceAboveSurfaceEnumerator(Type_ShapeFileLayer par) 
			{
                this.parent = par;
                this.nIndex = -1;
			}
			public void Reset() 
			{
                this.nIndex = -1;
			}
			public bool MoveNext() 
			{
                this.nIndex++;
				return(this.nIndex < this.parent.DistanceAboveSurfaceCount );
			}
			public SchemaDecimal  Current 
			{
				get 
				{
					return(this.parent.GetDistanceAboveSurfaceAt(this.nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(this.Current);
				}
			}
    	}

        #endregion // DistanceAboveSurface collection

		#region MasterFilePath accessor methods
		public int GetMasterFilePathMinCount()
		{
			return 1;
		}

		public int MasterFilePathMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetMasterFilePathMaxCount()
		{
			return 1;
		}

		public int MasterFilePathMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetMasterFilePathCount()
		{
			return this.DomChildCount(NodeType.Element, "", "MasterFilePath");
		}

		public int MasterFilePathCount
		{
			get
			{
				return this.DomChildCount(NodeType.Element, "", "MasterFilePath");
			}
		}

		public bool HasMasterFilePath()
		{
			return this.HasDomChild(NodeType.Element, "", "MasterFilePath");
		}

		public SchemaString GetMasterFilePathAt(int index)
		{
			return new SchemaString(GetDomNodeValue(this.GetDomChildAt(NodeType.Element, "", "MasterFilePath", index)));
		}

		public XmlNode GetStartingMasterFilePathCursor()
		{
			return this.GetDomFirstChild( NodeType.Element, "", "MasterFilePath" );
		}

		public XmlNode GetAdvancedMasterFilePathCursor( XmlNode curNode )
		{
			return this.GetDomNextChild( NodeType.Element, "", "MasterFilePath", curNode );
		}

		public SchemaString GetMasterFilePathValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaString( curNode.InnerText );
		}


		public SchemaString GetMasterFilePath()
		{
			return this.GetMasterFilePathAt(0);
		}

		public SchemaString MasterFilePath
		{
			get
			{
				return this.GetMasterFilePathAt(0);
			}
		}

		public void RemoveMasterFilePathAt(int index)
		{
            this.RemoveDomChildAt(NodeType.Element, "", "MasterFilePath", index);
		}

		public void RemoveMasterFilePath()
		{
			while (this.HasMasterFilePath()) this.RemoveMasterFilePathAt(0);
		}

		public void AddMasterFilePath(SchemaString newValue)
		{
            this.AppendDomChild(NodeType.Element, "", "MasterFilePath", newValue.ToString());
		}

		public void InsertMasterFilePathAt(SchemaString newValue, int index)
		{
            this.InsertDomChildAt(NodeType.Element, "", "MasterFilePath", index, newValue.ToString());
		}

		public void ReplaceMasterFilePathAt(SchemaString newValue, int index)
		{
            this.ReplaceDomChildAt(NodeType.Element, "", "MasterFilePath", index, newValue.ToString());
		}
		#endregion // MasterFilePath accessor methods

		#region MasterFilePath collection
        public MasterFilePathCollection	MyMasterFilePaths = new MasterFilePathCollection( );

        public class MasterFilePathCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
                    this.parent = value;
				}
			}
			public MasterFilePathEnumerator GetEnumerator() 
			{
				return new MasterFilePathEnumerator(this.parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return this.GetEnumerator();
			}
        }

        public class MasterFilePathEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public MasterFilePathEnumerator(Type_ShapeFileLayer par) 
			{
                this.parent = par;
                this.nIndex = -1;
			}
			public void Reset() 
			{
                this.nIndex = -1;
			}
			public bool MoveNext() 
			{
                this.nIndex++;
				return(this.nIndex < this.parent.MasterFilePathCount );
			}
			public SchemaString  Current 
			{
				get 
				{
					return(this.parent.GetMasterFilePathAt(this.nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(this.Current);
				}
			}
    	}

        #endregion // MasterFilePath collection

		#region MinimumViewAltitude accessor methods
		public int GetMinimumViewAltitudeMinCount()
		{
			return 1;
		}

		public int MinimumViewAltitudeMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetMinimumViewAltitudeMaxCount()
		{
			return 1;
		}

		public int MinimumViewAltitudeMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetMinimumViewAltitudeCount()
		{
			return this.DomChildCount(NodeType.Element, "", "MinimumViewAltitude");
		}

		public int MinimumViewAltitudeCount
		{
			get
			{
				return this.DomChildCount(NodeType.Element, "", "MinimumViewAltitude");
			}
		}

		public bool HasMinimumViewAltitude()
		{
			return this.HasDomChild(NodeType.Element, "", "MinimumViewAltitude");
		}

		public SchemaDecimal GetMinimumViewAltitudeAt(int index)
		{
			return new SchemaDecimal(GetDomNodeValue(this.GetDomChildAt(NodeType.Element, "", "MinimumViewAltitude", index)));
		}

		public XmlNode GetStartingMinimumViewAltitudeCursor()
		{
			return this.GetDomFirstChild( NodeType.Element, "", "MinimumViewAltitude" );
		}

		public XmlNode GetAdvancedMinimumViewAltitudeCursor( XmlNode curNode )
		{
			return this.GetDomNextChild( NodeType.Element, "", "MinimumViewAltitude", curNode );
		}

		public SchemaDecimal GetMinimumViewAltitudeValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaDecimal( curNode.InnerText );
		}


		public SchemaDecimal GetMinimumViewAltitude()
		{
			return this.GetMinimumViewAltitudeAt(0);
		}

		public SchemaDecimal MinimumViewAltitude
		{
			get
			{
				return this.GetMinimumViewAltitudeAt(0);
			}
		}

		public void RemoveMinimumViewAltitudeAt(int index)
		{
            this.RemoveDomChildAt(NodeType.Element, "", "MinimumViewAltitude", index);
		}

		public void RemoveMinimumViewAltitude()
		{
			while (this.HasMinimumViewAltitude()) this.RemoveMinimumViewAltitudeAt(0);
		}

		public void AddMinimumViewAltitude(SchemaDecimal newValue)
		{
            this.AppendDomChild(NodeType.Element, "", "MinimumViewAltitude", newValue.ToString());
		}

		public void InsertMinimumViewAltitudeAt(SchemaDecimal newValue, int index)
		{
            this.InsertDomChildAt(NodeType.Element, "", "MinimumViewAltitude", index, newValue.ToString());
		}

		public void ReplaceMinimumViewAltitudeAt(SchemaDecimal newValue, int index)
		{
            this.ReplaceDomChildAt(NodeType.Element, "", "MinimumViewAltitude", index, newValue.ToString());
		}
		#endregion // MinimumViewAltitude accessor methods

		#region MinimumViewAltitude collection
        public MinimumViewAltitudeCollection	MyMinimumViewAltitudes = new MinimumViewAltitudeCollection( );

        public class MinimumViewAltitudeCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
                    this.parent = value;
				}
			}
			public MinimumViewAltitudeEnumerator GetEnumerator() 
			{
				return new MinimumViewAltitudeEnumerator(this.parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return this.GetEnumerator();
			}
        }

        public class MinimumViewAltitudeEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public MinimumViewAltitudeEnumerator(Type_ShapeFileLayer par) 
			{
                this.parent = par;
                this.nIndex = -1;
			}
			public void Reset() 
			{
                this.nIndex = -1;
			}
			public bool MoveNext() 
			{
                this.nIndex++;
				return(this.nIndex < this.parent.MinimumViewAltitudeCount );
			}
			public SchemaDecimal  Current 
			{
				get 
				{
					return(this.parent.GetMinimumViewAltitudeAt(this.nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(this.Current);
				}
			}
    	}

        #endregion // MinimumViewAltitude collection

		#region MaximumViewAltitude accessor methods
		public int GetMaximumViewAltitudeMinCount()
		{
			return 1;
		}

		public int MaximumViewAltitudeMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetMaximumViewAltitudeMaxCount()
		{
			return 1;
		}

		public int MaximumViewAltitudeMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetMaximumViewAltitudeCount()
		{
			return this.DomChildCount(NodeType.Element, "", "MaximumViewAltitude");
		}

		public int MaximumViewAltitudeCount
		{
			get
			{
				return this.DomChildCount(NodeType.Element, "", "MaximumViewAltitude");
			}
		}

		public bool HasMaximumViewAltitude()
		{
			return this.HasDomChild(NodeType.Element, "", "MaximumViewAltitude");
		}

		public SchemaDecimal GetMaximumViewAltitudeAt(int index)
		{
			return new SchemaDecimal(GetDomNodeValue(this.GetDomChildAt(NodeType.Element, "", "MaximumViewAltitude", index)));
		}

		public XmlNode GetStartingMaximumViewAltitudeCursor()
		{
			return this.GetDomFirstChild( NodeType.Element, "", "MaximumViewAltitude" );
		}

		public XmlNode GetAdvancedMaximumViewAltitudeCursor( XmlNode curNode )
		{
			return this.GetDomNextChild( NodeType.Element, "", "MaximumViewAltitude", curNode );
		}

		public SchemaDecimal GetMaximumViewAltitudeValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaDecimal( curNode.InnerText );
		}


		public SchemaDecimal GetMaximumViewAltitude()
		{
			return this.GetMaximumViewAltitudeAt(0);
		}

		public SchemaDecimal MaximumViewAltitude
		{
			get
			{
				return this.GetMaximumViewAltitudeAt(0);
			}
		}

		public void RemoveMaximumViewAltitudeAt(int index)
		{
            this.RemoveDomChildAt(NodeType.Element, "", "MaximumViewAltitude", index);
		}

		public void RemoveMaximumViewAltitude()
		{
			while (this.HasMaximumViewAltitude()) this.RemoveMaximumViewAltitudeAt(0);
		}

		public void AddMaximumViewAltitude(SchemaDecimal newValue)
		{
            this.AppendDomChild(NodeType.Element, "", "MaximumViewAltitude", newValue.ToString());
		}

		public void InsertMaximumViewAltitudeAt(SchemaDecimal newValue, int index)
		{
            this.InsertDomChildAt(NodeType.Element, "", "MaximumViewAltitude", index, newValue.ToString());
		}

		public void ReplaceMaximumViewAltitudeAt(SchemaDecimal newValue, int index)
		{
            this.ReplaceDomChildAt(NodeType.Element, "", "MaximumViewAltitude", index, newValue.ToString());
		}
		#endregion // MaximumViewAltitude accessor methods

		#region MaximumViewAltitude collection
        public MaximumViewAltitudeCollection	MyMaximumViewAltitudes = new MaximumViewAltitudeCollection( );

        public class MaximumViewAltitudeCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
                    this.parent = value;
				}
			}
			public MaximumViewAltitudeEnumerator GetEnumerator() 
			{
				return new MaximumViewAltitudeEnumerator(this.parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return this.GetEnumerator();
			}
        }

        public class MaximumViewAltitudeEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public MaximumViewAltitudeEnumerator(Type_ShapeFileLayer par) 
			{
                this.parent = par;
                this.nIndex = -1;
			}
			public void Reset() 
			{
                this.nIndex = -1;
			}
			public bool MoveNext() 
			{
                this.nIndex++;
				return(this.nIndex < this.parent.MaximumViewAltitudeCount );
			}
			public SchemaDecimal  Current 
			{
				get 
				{
					return(this.parent.GetMaximumViewAltitudeAt(this.nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(this.Current);
				}
			}
    	}

        #endregion // MaximumViewAltitude collection

		#region ShowPoints accessor methods
		public int GetShowPointsMinCount()
		{
			return 0;
		}

		public int ShowPointsMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetShowPointsMaxCount()
		{
			return 1;
		}

		public int ShowPointsMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetShowPointsCount()
		{
			return this.DomChildCount(NodeType.Element, "", "ShowPoints");
		}

		public int ShowPointsCount
		{
			get
			{
				return this.DomChildCount(NodeType.Element, "", "ShowPoints");
			}
		}

		public bool HasShowPoints()
		{
			return this.HasDomChild(NodeType.Element, "", "ShowPoints");
		}

		public SchemaBoolean GetShowPointsAt(int index)
		{
			return new SchemaBoolean(GetDomNodeValue(this.GetDomChildAt(NodeType.Element, "", "ShowPoints", index)));
		}

		public XmlNode GetStartingShowPointsCursor()
		{
			return this.GetDomFirstChild( NodeType.Element, "", "ShowPoints" );
		}

		public XmlNode GetAdvancedShowPointsCursor( XmlNode curNode )
		{
			return this.GetDomNextChild( NodeType.Element, "", "ShowPoints", curNode );
		}

		public SchemaBoolean GetShowPointsValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaBoolean( curNode.InnerText );
		}


		public SchemaBoolean GetShowPoints()
		{
			return this.GetShowPointsAt(0);
		}

		public SchemaBoolean ShowPoints
		{
			get
			{
				return this.GetShowPointsAt(0);
			}
		}

		public void RemoveShowPointsAt(int index)
		{
            this.RemoveDomChildAt(NodeType.Element, "", "ShowPoints", index);
		}

		public void RemoveShowPoints()
		{
			while (this.HasShowPoints()) this.RemoveShowPointsAt(0);
		}

		public void AddShowPoints(SchemaBoolean newValue)
		{
            this.AppendDomChild(NodeType.Element, "", "ShowPoints", newValue.ToString());
		}

		public void InsertShowPointsAt(SchemaBoolean newValue, int index)
		{
            this.InsertDomChildAt(NodeType.Element, "", "ShowPoints", index, newValue.ToString());
		}

		public void ReplaceShowPointsAt(SchemaBoolean newValue, int index)
		{
            this.ReplaceDomChildAt(NodeType.Element, "", "ShowPoints", index, newValue.ToString());
		}
		#endregion // ShowPoints accessor methods

		#region ShowPoints collection
        public ShowPointsCollection	MyShowPointss = new ShowPointsCollection( );

        public class ShowPointsCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
                    this.parent = value;
				}
			}
			public ShowPointsEnumerator GetEnumerator() 
			{
				return new ShowPointsEnumerator(this.parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return this.GetEnumerator();
			}
        }

        public class ShowPointsEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public ShowPointsEnumerator(Type_ShapeFileLayer par) 
			{
                this.parent = par;
                this.nIndex = -1;
			}
			public void Reset() 
			{
                this.nIndex = -1;
			}
			public bool MoveNext() 
			{
                this.nIndex++;
				return(this.nIndex < this.parent.ShowPointsCount );
			}
			public SchemaBoolean  Current 
			{
				get 
				{
					return(this.parent.GetShowPointsAt(this.nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(this.Current);
				}
			}
    	}

        #endregion // ShowPoints collection

		#region ShowBoundaries accessor methods
		public int GetShowBoundariesMinCount()
		{
			return 0;
		}

		public int ShowBoundariesMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetShowBoundariesMaxCount()
		{
			return 1;
		}

		public int ShowBoundariesMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetShowBoundariesCount()
		{
			return this.DomChildCount(NodeType.Element, "", "ShowBoundaries");
		}

		public int ShowBoundariesCount
		{
			get
			{
				return this.DomChildCount(NodeType.Element, "", "ShowBoundaries");
			}
		}

		public bool HasShowBoundaries()
		{
			return this.HasDomChild(NodeType.Element, "", "ShowBoundaries");
		}

		public SchemaBoolean GetShowBoundariesAt(int index)
		{
			return new SchemaBoolean(GetDomNodeValue(this.GetDomChildAt(NodeType.Element, "", "ShowBoundaries", index)));
		}

		public XmlNode GetStartingShowBoundariesCursor()
		{
			return this.GetDomFirstChild( NodeType.Element, "", "ShowBoundaries" );
		}

		public XmlNode GetAdvancedShowBoundariesCursor( XmlNode curNode )
		{
			return this.GetDomNextChild( NodeType.Element, "", "ShowBoundaries", curNode );
		}

		public SchemaBoolean GetShowBoundariesValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaBoolean( curNode.InnerText );
		}


		public SchemaBoolean GetShowBoundaries()
		{
			return this.GetShowBoundariesAt(0);
		}

		public SchemaBoolean ShowBoundaries
		{
			get
			{
				return this.GetShowBoundariesAt(0);
			}
		}

		public void RemoveShowBoundariesAt(int index)
		{
            this.RemoveDomChildAt(NodeType.Element, "", "ShowBoundaries", index);
		}

		public void RemoveShowBoundaries()
		{
			while (this.HasShowBoundaries()) this.RemoveShowBoundariesAt(0);
		}

		public void AddShowBoundaries(SchemaBoolean newValue)
		{
            this.AppendDomChild(NodeType.Element, "", "ShowBoundaries", newValue.ToString());
		}

		public void InsertShowBoundariesAt(SchemaBoolean newValue, int index)
		{
            this.InsertDomChildAt(NodeType.Element, "", "ShowBoundaries", index, newValue.ToString());
		}

		public void ReplaceShowBoundariesAt(SchemaBoolean newValue, int index)
		{
            this.ReplaceDomChildAt(NodeType.Element, "", "ShowBoundaries", index, newValue.ToString());
		}
		#endregion // ShowBoundaries accessor methods

		#region ShowBoundaries collection
        public ShowBoundariesCollection	MyShowBoundariess = new ShowBoundariesCollection( );

        public class ShowBoundariesCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
                    this.parent = value;
				}
			}
			public ShowBoundariesEnumerator GetEnumerator() 
			{
				return new ShowBoundariesEnumerator(this.parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return this.GetEnumerator();
			}
        }

        public class ShowBoundariesEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public ShowBoundariesEnumerator(Type_ShapeFileLayer par) 
			{
                this.parent = par;
                this.nIndex = -1;
			}
			public void Reset() 
			{
                this.nIndex = -1;
			}
			public bool MoveNext() 
			{
                this.nIndex++;
				return(this.nIndex < this.parent.ShowBoundariesCount );
			}
			public SchemaBoolean  Current 
			{
				get 
				{
					return(this.parent.GetShowBoundariesAt(this.nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(this.Current);
				}
			}
    	}

        #endregion // ShowBoundaries collection

		#region ShowFilledRegions accessor methods
		public int GetShowFilledRegionsMinCount()
		{
			return 0;
		}

		public int ShowFilledRegionsMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetShowFilledRegionsMaxCount()
		{
			return 1;
		}

		public int ShowFilledRegionsMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetShowFilledRegionsCount()
		{
			return this.DomChildCount(NodeType.Element, "", "ShowFilledRegions");
		}

		public int ShowFilledRegionsCount
		{
			get
			{
				return this.DomChildCount(NodeType.Element, "", "ShowFilledRegions");
			}
		}

		public bool HasShowFilledRegions()
		{
			return this.HasDomChild(NodeType.Element, "", "ShowFilledRegions");
		}

		public SchemaBoolean GetShowFilledRegionsAt(int index)
		{
			return new SchemaBoolean(GetDomNodeValue(this.GetDomChildAt(NodeType.Element, "", "ShowFilledRegions", index)));
		}

		public XmlNode GetStartingShowFilledRegionsCursor()
		{
			return this.GetDomFirstChild( NodeType.Element, "", "ShowFilledRegions" );
		}

		public XmlNode GetAdvancedShowFilledRegionsCursor( XmlNode curNode )
		{
			return this.GetDomNextChild( NodeType.Element, "", "ShowFilledRegions", curNode );
		}

		public SchemaBoolean GetShowFilledRegionsValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaBoolean( curNode.InnerText );
		}


		public SchemaBoolean GetShowFilledRegions()
		{
			return this.GetShowFilledRegionsAt(0);
		}

		public SchemaBoolean ShowFilledRegions
		{
			get
			{
				return this.GetShowFilledRegionsAt(0);
			}
		}

		public void RemoveShowFilledRegionsAt(int index)
		{
            this.RemoveDomChildAt(NodeType.Element, "", "ShowFilledRegions", index);
		}

		public void RemoveShowFilledRegions()
		{
			while (this.HasShowFilledRegions()) this.RemoveShowFilledRegionsAt(0);
		}

		public void AddShowFilledRegions(SchemaBoolean newValue)
		{
            this.AppendDomChild(NodeType.Element, "", "ShowFilledRegions", newValue.ToString());
		}

		public void InsertShowFilledRegionsAt(SchemaBoolean newValue, int index)
		{
            this.InsertDomChildAt(NodeType.Element, "", "ShowFilledRegions", index, newValue.ToString());
		}

		public void ReplaceShowFilledRegionsAt(SchemaBoolean newValue, int index)
		{
            this.ReplaceDomChildAt(NodeType.Element, "", "ShowFilledRegions", index, newValue.ToString());
		}
		#endregion // ShowFilledRegions accessor methods

		#region ShowFilledRegions collection
        public ShowFilledRegionsCollection	MyShowFilledRegionss = new ShowFilledRegionsCollection( );

        public class ShowFilledRegionsCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
                    this.parent = value;
				}
			}
			public ShowFilledRegionsEnumerator GetEnumerator() 
			{
				return new ShowFilledRegionsEnumerator(this.parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return this.GetEnumerator();
			}
        }

        public class ShowFilledRegionsEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public ShowFilledRegionsEnumerator(Type_ShapeFileLayer par) 
			{
                this.parent = par;
                this.nIndex = -1;
			}
			public void Reset() 
			{
                this.nIndex = -1;
			}
			public bool MoveNext() 
			{
                this.nIndex++;
				return(this.nIndex < this.parent.ShowFilledRegionsCount );
			}
			public SchemaBoolean  Current 
			{
				get 
				{
					return(this.parent.GetShowFilledRegionsAt(this.nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(this.Current);
				}
			}
    	}

        #endregion // ShowFilledRegions collection

		#region ScalarKey accessor methods
		public int GetScalarKeyMinCount()
		{
			return 0;
		}

		public int ScalarKeyMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetScalarKeyMaxCount()
		{
			return 1;
		}

		public int ScalarKeyMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetScalarKeyCount()
		{
			return this.DomChildCount(NodeType.Element, "", "ScalarKey");
		}

		public int ScalarKeyCount
		{
			get
			{
				return this.DomChildCount(NodeType.Element, "", "ScalarKey");
			}
		}

		public bool HasScalarKey()
		{
			return this.HasDomChild(NodeType.Element, "", "ScalarKey");
		}

		public SchemaString GetScalarKeyAt(int index)
		{
			return new SchemaString(GetDomNodeValue(this.GetDomChildAt(NodeType.Element, "", "ScalarKey", index)));
		}

		public XmlNode GetStartingScalarKeyCursor()
		{
			return this.GetDomFirstChild( NodeType.Element, "", "ScalarKey" );
		}

		public XmlNode GetAdvancedScalarKeyCursor( XmlNode curNode )
		{
			return this.GetDomNextChild( NodeType.Element, "", "ScalarKey", curNode );
		}

		public SchemaString GetScalarKeyValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaString( curNode.InnerText );
		}


		public SchemaString GetScalarKey()
		{
			return this.GetScalarKeyAt(0);
		}

		public SchemaString ScalarKey
		{
			get
			{
				return this.GetScalarKeyAt(0);
			}
		}

		public void RemoveScalarKeyAt(int index)
		{
            this.RemoveDomChildAt(NodeType.Element, "", "ScalarKey", index);
		}

		public void RemoveScalarKey()
		{
			while (this.HasScalarKey()) this.RemoveScalarKeyAt(0);
		}

		public void AddScalarKey(SchemaString newValue)
		{
            this.AppendDomChild(NodeType.Element, "", "ScalarKey", newValue.ToString());
		}

		public void InsertScalarKeyAt(SchemaString newValue, int index)
		{
            this.InsertDomChildAt(NodeType.Element, "", "ScalarKey", index, newValue.ToString());
		}

		public void ReplaceScalarKeyAt(SchemaString newValue, int index)
		{
            this.ReplaceDomChildAt(NodeType.Element, "", "ScalarKey", index, newValue.ToString());
		}
		#endregion // ScalarKey accessor methods

		#region ScalarKey collection
        public ScalarKeyCollection	MyScalarKeys = new ScalarKeyCollection( );

        public class ScalarKeyCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
                    this.parent = value;
				}
			}
			public ScalarKeyEnumerator GetEnumerator() 
			{
				return new ScalarKeyEnumerator(this.parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return this.GetEnumerator();
			}
        }

        public class ScalarKeyEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public ScalarKeyEnumerator(Type_ShapeFileLayer par) 
			{
                this.parent = par;
                this.nIndex = -1;
			}
			public void Reset() 
			{
                this.nIndex = -1;
			}
			public bool MoveNext() 
			{
                this.nIndex++;
				return(this.nIndex < this.parent.ScalarKeyCount );
			}
			public SchemaString  Current 
			{
				get 
				{
					return(this.parent.GetScalarKeyAt(this.nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(this.Current);
				}
			}
    	}

        #endregion // ScalarKey collection

		#region ShowScalarValues accessor methods
		public int GetShowScalarValuesMinCount()
		{
			return 0;
		}

		public int ShowScalarValuesMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetShowScalarValuesMaxCount()
		{
			return 1;
		}

		public int ShowScalarValuesMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetShowScalarValuesCount()
		{
			return this.DomChildCount(NodeType.Element, "", "ShowScalarValues");
		}

		public int ShowScalarValuesCount
		{
			get
			{
				return this.DomChildCount(NodeType.Element, "", "ShowScalarValues");
			}
		}

		public bool HasShowScalarValues()
		{
			return this.HasDomChild(NodeType.Element, "", "ShowScalarValues");
		}

		public SchemaBoolean GetShowScalarValuesAt(int index)
		{
			return new SchemaBoolean(GetDomNodeValue(this.GetDomChildAt(NodeType.Element, "", "ShowScalarValues", index)));
		}

		public XmlNode GetStartingShowScalarValuesCursor()
		{
			return this.GetDomFirstChild( NodeType.Element, "", "ShowScalarValues" );
		}

		public XmlNode GetAdvancedShowScalarValuesCursor( XmlNode curNode )
		{
			return this.GetDomNextChild( NodeType.Element, "", "ShowScalarValues", curNode );
		}

		public SchemaBoolean GetShowScalarValuesValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaBoolean( curNode.InnerText );
		}


		public SchemaBoolean GetShowScalarValues()
		{
			return this.GetShowScalarValuesAt(0);
		}

		public SchemaBoolean ShowScalarValues
		{
			get
			{
				return this.GetShowScalarValuesAt(0);
			}
		}

		public void RemoveShowScalarValuesAt(int index)
		{
            this.RemoveDomChildAt(NodeType.Element, "", "ShowScalarValues", index);
		}

		public void RemoveShowScalarValues()
		{
			while (this.HasShowScalarValues()) this.RemoveShowScalarValuesAt(0);
		}

		public void AddShowScalarValues(SchemaBoolean newValue)
		{
            this.AppendDomChild(NodeType.Element, "", "ShowScalarValues", newValue.ToString());
		}

		public void InsertShowScalarValuesAt(SchemaBoolean newValue, int index)
		{
            this.InsertDomChildAt(NodeType.Element, "", "ShowScalarValues", index, newValue.ToString());
		}

		public void ReplaceShowScalarValuesAt(SchemaBoolean newValue, int index)
		{
            this.ReplaceDomChildAt(NodeType.Element, "", "ShowScalarValues", index, newValue.ToString());
		}
		#endregion // ShowScalarValues accessor methods

		#region ShowScalarValues collection
        public ShowScalarValuesCollection	MyShowScalarValuess = new ShowScalarValuesCollection( );

        public class ShowScalarValuesCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
                    this.parent = value;
				}
			}
			public ShowScalarValuesEnumerator GetEnumerator() 
			{
				return new ShowScalarValuesEnumerator(this.parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return this.GetEnumerator();
			}
        }

        public class ShowScalarValuesEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public ShowScalarValuesEnumerator(Type_ShapeFileLayer par) 
			{
                this.parent = par;
                this.nIndex = -1;
			}
			public void Reset() 
			{
                this.nIndex = -1;
			}
			public bool MoveNext() 
			{
                this.nIndex++;
				return(this.nIndex < this.parent.ShowScalarValuesCount );
			}
			public SchemaBoolean  Current 
			{
				get 
				{
					return(this.parent.GetShowScalarValuesAt(this.nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(this.Current);
				}
			}
    	}

        #endregion // ShowScalarValues collection

		#region DisplayFont accessor methods
		public int GetDisplayFontMinCount()
		{
			return 0;
		}

		public int DisplayFontMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetDisplayFontMaxCount()
		{
			return 1;
		}

		public int DisplayFontMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetDisplayFontCount()
		{
			return this.DomChildCount(NodeType.Element, "", "DisplayFont");
		}

		public int DisplayFontCount
		{
			get
			{
				return this.DomChildCount(NodeType.Element, "", "DisplayFont");
			}
		}

		public bool HasDisplayFont()
		{
			return this.HasDomChild(NodeType.Element, "", "DisplayFont");
		}

		public Type_DisplayFont2 GetDisplayFontAt(int index)
		{
			return new Type_DisplayFont2(this.GetDomChildAt(NodeType.Element, "", "DisplayFont", index));
		}

		public XmlNode GetStartingDisplayFontCursor()
		{
			return this.GetDomFirstChild( NodeType.Element, "", "DisplayFont" );
		}

		public XmlNode GetAdvancedDisplayFontCursor( XmlNode curNode )
		{
			return this.GetDomNextChild( NodeType.Element, "", "DisplayFont", curNode );
		}

		public Type_DisplayFont2 GetDisplayFontValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new Type_DisplayFont2( curNode );
		}


		public Type_DisplayFont2 GetDisplayFont()
		{
			return this.GetDisplayFontAt(0);
		}

		public Type_DisplayFont2 DisplayFont
		{
			get
			{
				return this.GetDisplayFontAt(0);
			}
		}

		public void RemoveDisplayFontAt(int index)
		{
            this.RemoveDomChildAt(NodeType.Element, "", "DisplayFont", index);
		}

		public void RemoveDisplayFont()
		{
			while (this.HasDisplayFont()) this.RemoveDisplayFontAt(0);
		}

		public void AddDisplayFont(Type_DisplayFont2 newValue)
		{
            this.AppendDomElement("", "DisplayFont", newValue);
		}

		public void InsertDisplayFontAt(Type_DisplayFont2 newValue, int index)
		{
            this.InsertDomElementAt("", "DisplayFont", index, newValue);
		}

		public void ReplaceDisplayFontAt(Type_DisplayFont2 newValue, int index)
		{
            this.ReplaceDomElementAt("", "DisplayFont", index, newValue);
		}
		#endregion // DisplayFont accessor methods

		#region DisplayFont collection
        public DisplayFontCollection	MyDisplayFonts = new DisplayFontCollection( );

        public class DisplayFontCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
                    this.parent = value;
				}
			}
			public DisplayFontEnumerator GetEnumerator() 
			{
				return new DisplayFontEnumerator(this.parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return this.GetEnumerator();
			}
        }

        public class DisplayFontEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public DisplayFontEnumerator(Type_ShapeFileLayer par) 
			{
                this.parent = par;
                this.nIndex = -1;
			}
			public void Reset() 
			{
                this.nIndex = -1;
			}
			public bool MoveNext() 
			{
                this.nIndex++;
				return(this.nIndex < this.parent.DisplayFontCount );
			}
			public Type_DisplayFont2  Current 
			{
				get 
				{
					return(this.parent.GetDisplayFontAt(this.nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(this.Current);
				}
			}
    	}

        #endregion // DisplayFont collection

		#region RGBColor accessor methods
		public int GetRGBColorMinCount()
		{
			return 0;
		}

		public int RGBColorMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetRGBColorMaxCount()
		{
			return 1;
		}

		public int RGBColorMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetRGBColorCount()
		{
			return this.DomChildCount(NodeType.Element, "", "RGBColor");
		}

		public int RGBColorCount
		{
			get
			{
				return this.DomChildCount(NodeType.Element, "", "RGBColor");
			}
		}

		public bool HasRGBColor()
		{
			return this.HasDomChild(NodeType.Element, "", "RGBColor");
		}

		public Type_RGBColor2 GetRGBColorAt(int index)
		{
			return new Type_RGBColor2(this.GetDomChildAt(NodeType.Element, "", "RGBColor", index));
		}

		public XmlNode GetStartingRGBColorCursor()
		{
			return this.GetDomFirstChild( NodeType.Element, "", "RGBColor" );
		}

		public XmlNode GetAdvancedRGBColorCursor( XmlNode curNode )
		{
			return this.GetDomNextChild( NodeType.Element, "", "RGBColor", curNode );
		}

		public Type_RGBColor2 GetRGBColorValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new Type_RGBColor2( curNode );
		}


		public Type_RGBColor2 GetRGBColor()
		{
			return this.GetRGBColorAt(0);
		}

		public Type_RGBColor2 RGBColor
		{
			get
			{
				return this.GetRGBColorAt(0);
			}
		}

		public void RemoveRGBColorAt(int index)
		{
            this.RemoveDomChildAt(NodeType.Element, "", "RGBColor", index);
		}

		public void RemoveRGBColor()
		{
			while (this.HasRGBColor()) this.RemoveRGBColorAt(0);
		}

		public void AddRGBColor(Type_RGBColor2 newValue)
		{
            this.AppendDomElement("", "RGBColor", newValue);
		}

		public void InsertRGBColorAt(Type_RGBColor2 newValue, int index)
		{
            this.InsertDomElementAt("", "RGBColor", index, newValue);
		}

		public void ReplaceRGBColorAt(Type_RGBColor2 newValue, int index)
		{
            this.ReplaceDomElementAt("", "RGBColor", index, newValue);
		}
		#endregion // RGBColor accessor methods

		#region RGBColor collection
        public RGBColorCollection	MyRGBColors = new RGBColorCollection( );

        public class RGBColorCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
                    this.parent = value;
				}
			}
			public RGBColorEnumerator GetEnumerator() 
			{
				return new RGBColorEnumerator(this.parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return this.GetEnumerator();
			}
        }

        public class RGBColorEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public RGBColorEnumerator(Type_ShapeFileLayer par) 
			{
                this.parent = par;
                this.nIndex = -1;
			}
			public void Reset() 
			{
                this.nIndex = -1;
			}
			public bool MoveNext() 
			{
                this.nIndex++;
				return(this.nIndex < this.parent.RGBColorCount );
			}
			public Type_RGBColor2  Current 
			{
				get 
				{
					return(this.parent.GetRGBColorAt(this.nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(this.Current);
				}
			}
    	}

        #endregion // RGBColor collection

		#region WinColorName accessor methods
		public int GetWinColorNameMinCount()
		{
			return 0;
		}

		public int WinColorNameMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetWinColorNameMaxCount()
		{
			return 1;
		}

		public int WinColorNameMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetWinColorNameCount()
		{
			return this.DomChildCount(NodeType.Element, "", "WinColorName");
		}

		public int WinColorNameCount
		{
			get
			{
				return this.DomChildCount(NodeType.Element, "", "WinColorName");
			}
		}

		public bool HasWinColorName()
		{
			return this.HasDomChild(NodeType.Element, "", "WinColorName");
		}

		public SchemaString GetWinColorNameAt(int index)
		{
			return new SchemaString(GetDomNodeValue(this.GetDomChildAt(NodeType.Element, "", "WinColorName", index)));
		}

		public XmlNode GetStartingWinColorNameCursor()
		{
			return this.GetDomFirstChild( NodeType.Element, "", "WinColorName" );
		}

		public XmlNode GetAdvancedWinColorNameCursor( XmlNode curNode )
		{
			return this.GetDomNextChild( NodeType.Element, "", "WinColorName", curNode );
		}

		public SchemaString GetWinColorNameValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new SchemaString( curNode.InnerText );
		}


		public SchemaString GetWinColorName()
		{
			return this.GetWinColorNameAt(0);
		}

		public SchemaString WinColorName
		{
			get
			{
				return this.GetWinColorNameAt(0);
			}
		}

		public void RemoveWinColorNameAt(int index)
		{
            this.RemoveDomChildAt(NodeType.Element, "", "WinColorName", index);
		}

		public void RemoveWinColorName()
		{
			while (this.HasWinColorName()) this.RemoveWinColorNameAt(0);
		}

		public void AddWinColorName(SchemaString newValue)
		{
            this.AppendDomChild(NodeType.Element, "", "WinColorName", newValue.ToString());
		}

		public void InsertWinColorNameAt(SchemaString newValue, int index)
		{
            this.InsertDomChildAt(NodeType.Element, "", "WinColorName", index, newValue.ToString());
		}

		public void ReplaceWinColorNameAt(SchemaString newValue, int index)
		{
            this.ReplaceDomChildAt(NodeType.Element, "", "WinColorName", index, newValue.ToString());
		}
		#endregion // WinColorName accessor methods

		#region WinColorName collection
        public WinColorNameCollection	MyWinColorNames = new WinColorNameCollection( );

        public class WinColorNameCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
                    this.parent = value;
				}
			}
			public WinColorNameEnumerator GetEnumerator() 
			{
				return new WinColorNameEnumerator(this.parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return this.GetEnumerator();
			}
        }

        public class WinColorNameEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public WinColorNameEnumerator(Type_ShapeFileLayer par) 
			{
                this.parent = par;
                this.nIndex = -1;
			}
			public void Reset() 
			{
                this.nIndex = -1;
			}
			public bool MoveNext() 
			{
                this.nIndex++;
				return(this.nIndex < this.parent.WinColorNameCount );
			}
			public SchemaString  Current 
			{
				get 
				{
					return(this.parent.GetWinColorNameAt(this.nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(this.Current);
				}
			}
    	}

        #endregion // WinColorName collection

		#region ExtendedInformation accessor methods
		public int GetExtendedInformationMinCount()
		{
			return 0;
		}

		public int ExtendedInformationMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetExtendedInformationMaxCount()
		{
			return 1;
		}

		public int ExtendedInformationMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetExtendedInformationCount()
		{
			return this.DomChildCount(NodeType.Element, "", "ExtendedInformation");
		}

		public int ExtendedInformationCount
		{
			get
			{
				return this.DomChildCount(NodeType.Element, "", "ExtendedInformation");
			}
		}

		public bool HasExtendedInformation()
		{
			return this.HasDomChild(NodeType.Element, "", "ExtendedInformation");
		}

		public Type_ExtendedInformation GetExtendedInformationAt(int index)
		{
			return new Type_ExtendedInformation(this.GetDomChildAt(NodeType.Element, "", "ExtendedInformation", index));
		}

		public XmlNode GetStartingExtendedInformationCursor()
		{
			return this.GetDomFirstChild( NodeType.Element, "", "ExtendedInformation" );
		}

		public XmlNode GetAdvancedExtendedInformationCursor( XmlNode curNode )
		{
			return this.GetDomNextChild( NodeType.Element, "", "ExtendedInformation", curNode );
		}

		public Type_ExtendedInformation GetExtendedInformationValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.Xml.XmlException("Out of range");
			else
				return new Type_ExtendedInformation( curNode );
		}


		public Type_ExtendedInformation GetExtendedInformation()
		{
			return this.GetExtendedInformationAt(0);
		}

		public Type_ExtendedInformation ExtendedInformation
		{
			get
			{
				return this.GetExtendedInformationAt(0);
			}
		}

		public void RemoveExtendedInformationAt(int index)
		{
            this.RemoveDomChildAt(NodeType.Element, "", "ExtendedInformation", index);
		}

		public void RemoveExtendedInformation()
		{
			while (this.HasExtendedInformation()) this.RemoveExtendedInformationAt(0);
		}

		public void AddExtendedInformation(Type_ExtendedInformation newValue)
		{
            this.AppendDomElement("", "ExtendedInformation", newValue);
		}

		public void InsertExtendedInformationAt(Type_ExtendedInformation newValue, int index)
		{
            this.InsertDomElementAt("", "ExtendedInformation", index, newValue);
		}

		public void ReplaceExtendedInformationAt(Type_ExtendedInformation newValue, int index)
		{
            this.ReplaceDomElementAt("", "ExtendedInformation", index, newValue);
		}
		#endregion // ExtendedInformation accessor methods

		#region ExtendedInformation collection
        public ExtendedInformationCollection	MyExtendedInformations = new ExtendedInformationCollection( );

        public class ExtendedInformationCollection: IEnumerable
        {
            Type_ShapeFileLayer parent;
            public Type_ShapeFileLayer Parent
			{
				set
				{
                    this.parent = value;
				}
			}
			public ExtendedInformationEnumerator GetEnumerator() 
			{
				return new ExtendedInformationEnumerator(this.parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return this.GetEnumerator();
			}
        }

        public class ExtendedInformationEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ShapeFileLayer parent;
			public ExtendedInformationEnumerator(Type_ShapeFileLayer par) 
			{
                this.parent = par;
                this.nIndex = -1;
			}
			public void Reset() 
			{
                this.nIndex = -1;
			}
			public bool MoveNext() 
			{
                this.nIndex++;
				return(this.nIndex < this.parent.ExtendedInformationCount );
			}
			public Type_ExtendedInformation  Current 
			{
				get 
				{
					return(this.parent.GetExtendedInformationAt(this.nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(this.Current);
				}
			}
    	}

        #endregion // ExtendedInformation collection

        private void SetCollectionParents()
        {
            this.MyShowAtStartups.Parent = this;
            this.MyNames.Parent = this;
            this.MyDistanceAboveSurfaces.Parent = this;
            this.MyMasterFilePaths.Parent = this;
            this.MyMinimumViewAltitudes.Parent = this;
            this.MyMaximumViewAltitudes.Parent = this;
            this.MyShowPointss.Parent = this;
            this.MyShowBoundariess.Parent = this;
            this.MyShowFilledRegionss.Parent = this;
            this.MyScalarKeys.Parent = this;
            this.MyShowScalarValuess.Parent = this;
            this.MyDisplayFonts.Parent = this;
            this.MyRGBColors.Parent = this;
            this.MyWinColorNames.Parent = this;
            this.MyExtendedInformations.Parent = this; 
	}
}
}
