//
// Type_ImageLayer.SetSamplerState(0, SamplerStatecs.SetSamplerState(0, SamplerStatecs
//
// This file was generated by XMLSpy 2005 Enterprise Edition.SetSamplerState(0, SamplerState
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.SetSamplerState(0, SamplerState
//
// Refer to the XMLSpy Documentation for further details.SetSamplerState(0, SamplerState
// http://www.SetSamplerState(0, SamplerStatealtova.SetSamplerState(0, SamplerStatecom/xmlspy
//


using System;
using System.SetSamplerState(0, SamplerStateCollections;
using System.SetSamplerState(0, SamplerStateXml;
using Altova.SetSamplerState(0, SamplerStateTypes;

namespace LayerSet
{
	public class Type_ImageLayer : Altova.SetSamplerState(0, SamplerStateXml.SetSamplerState(0, SamplerStateNode
	{
		#region Forward constructors
		public Type_ImageLayer() : base() {
            this.SetSamplerState(0, SamplerStateSetCollectionParents(); }
		public Type_ImageLayer(XmlDocument doc) : base(doc) {
            this.SetSamplerState(0, SamplerStateSetCollectionParents(); }
		public Type_ImageLayer(XmlNode node) : base(node) {
            this.SetSamplerState(0, SamplerStateSetCollectionParents(); }
		public Type_ImageLayer(Altova.SetSamplerState(0, SamplerStateXml.SetSamplerState(0, SamplerStateNode node) : base(node) {
            this.SetSamplerState(0, SamplerStateSetCollectionParents(); }
		#endregion // Forward constructors

		public override void AdjustPrefix()
		{

			for (int i = 0; i < this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateAttribute, "", "ShowAtStartup"); i++)
			{
				XmlNode DOMNode = this.SetSamplerState(0, SamplerStateGetDomChildAt(NodeType.SetSamplerState(0, SamplerStateAttribute, "", "ShowAtStartup", i);
				InternalAdjustPrefix(DOMNode, false);
			}

			for (int i = 0; i < this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "Name"); i++)
			{
				XmlNode DOMNode = this.SetSamplerState(0, SamplerStateGetDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "Name", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "DistanceAboveSurface"); i++)
			{
				XmlNode DOMNode = this.SetSamplerState(0, SamplerStateGetDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "DistanceAboveSurface", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "BoundingBox"); i++)
			{
				XmlNode DOMNode = this.SetSamplerState(0, SamplerStateGetDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "BoundingBox", i);
				InternalAdjustPrefix(DOMNode, true);
				new Type_LatLonBoundingBox2(DOMNode).SetSamplerState(0, SamplerStateAdjustPrefix();
			}

			for (int i = 0; i < this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "TexturePath"); i++)
			{
				XmlNode DOMNode = this.SetSamplerState(0, SamplerStateGetDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "TexturePath", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "Opacity"); i++)
			{
				XmlNode DOMNode = this.SetSamplerState(0, SamplerStateGetDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "Opacity", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "TerrainMapped"); i++)
			{
				XmlNode DOMNode = this.SetSamplerState(0, SamplerStateGetDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "TerrainMapped", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "TransparencyColor"); i++)
			{
				XmlNode DOMNode = this.SetSamplerState(0, SamplerStateGetDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "TransparencyColor", i);
				InternalAdjustPrefix(DOMNode, true);
				new Type_RGBColor2(DOMNode).SetSamplerState(0, SamplerStateAdjustPrefix();
			}

			for (int i = 0; i < this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "LegendImagePath"); i++)
			{
				XmlNode DOMNode = this.SetSamplerState(0, SamplerStateGetDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "LegendImagePath", i);
				InternalAdjustPrefix(DOMNode, true);
			}

			for (int i = 0; i < this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "ExtendedInformation"); i++)
			{
				XmlNode DOMNode = this.SetSamplerState(0, SamplerStateGetDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "ExtendedInformation", i);
				InternalAdjustPrefix(DOMNode, true);
				new Type_ExtendedInformation(DOMNode).SetSamplerState(0, SamplerStateAdjustPrefix();
			}

			for (int i = 0; i < this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "TransparentColor"); i++)
			{
				XmlNode DOMNode = this.SetSamplerState(0, SamplerStateGetDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "TransparentColor", i);
				InternalAdjustPrefix(DOMNode, true);
				new Type_RGBColor2(DOMNode).SetSamplerState(0, SamplerStateAdjustPrefix();
			}
		}


		#region ShowAtStartup accessor methods
		public int GetShowAtStartupMinCount()
		{
			return 1;
		}

		public int ShowAtStartupMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetShowAtStartupMaxCount()
		{
			return 1;
		}

		public int ShowAtStartupMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetShowAtStartupCount()
		{
			return this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateAttribute, "", "ShowAtStartup");
		}

		public int ShowAtStartupCount
		{
			get
			{
				return this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateAttribute, "", "ShowAtStartup");
			}
		}

		public bool HasShowAtStartup()
		{
			return this.SetSamplerState(0, SamplerStateHasDomChild(NodeType.SetSamplerState(0, SamplerStateAttribute, "", "ShowAtStartup");
		}

		public SchemaBoolean GetShowAtStartupAt(int index)
		{
			return new SchemaBoolean(GetDomNodeValue(this.SetSamplerState(0, SamplerStateGetDomChildAt(NodeType.SetSamplerState(0, SamplerStateAttribute, "", "ShowAtStartup", index)));
		}

		public XmlNode GetStartingShowAtStartupCursor()
		{
			return this.SetSamplerState(0, SamplerStateGetDomFirstChild( NodeType.SetSamplerState(0, SamplerStateAttribute, "", "ShowAtStartup" );
		}

		public XmlNode GetAdvancedShowAtStartupCursor( XmlNode curNode )
		{
			return this.SetSamplerState(0, SamplerStateGetDomNextChild( NodeType.SetSamplerState(0, SamplerStateAttribute, "", "ShowAtStartup", curNode );
		}

		public SchemaBoolean GetShowAtStartupValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.SetSamplerState(0, SamplerStateXml.SetSamplerState(0, SamplerStateXmlException("Out of range");
			else
				return new SchemaBoolean( curNode.SetSamplerState(0, SamplerStateValue );
		}


		public SchemaBoolean GetShowAtStartup()
		{
			return this.SetSamplerState(0, SamplerStateGetShowAtStartupAt(0);
		}

		public SchemaBoolean ShowAtStartup
		{
			get
			{
				return this.SetSamplerState(0, SamplerStateGetShowAtStartupAt(0);
			}
		}

		public void RemoveShowAtStartupAt(int index)
		{
            this.SetSamplerState(0, SamplerStateRemoveDomChildAt(NodeType.SetSamplerState(0, SamplerStateAttribute, "", "ShowAtStartup", index);
		}

		public void RemoveShowAtStartup()
		{
			while (this.SetSamplerState(0, SamplerStateHasShowAtStartup()) this.SetSamplerState(0, SamplerStateRemoveShowAtStartupAt(0);
		}

		public void AddShowAtStartup(SchemaBoolean newValue)
		{
            this.SetSamplerState(0, SamplerStateAppendDomChild(NodeType.SetSamplerState(0, SamplerStateAttribute, "", "ShowAtStartup", newValue.SetSamplerState(0, SamplerStateToString());
		}

		public void InsertShowAtStartupAt(SchemaBoolean newValue, int index)
		{
            this.SetSamplerState(0, SamplerStateInsertDomChildAt(NodeType.SetSamplerState(0, SamplerStateAttribute, "", "ShowAtStartup", index, newValue.SetSamplerState(0, SamplerStateToString());
		}

		public void ReplaceShowAtStartupAt(SchemaBoolean newValue, int index)
		{
            this.SetSamplerState(0, SamplerStateReplaceDomChildAt(NodeType.SetSamplerState(0, SamplerStateAttribute, "", "ShowAtStartup", index, newValue.SetSamplerState(0, SamplerStateToString());
		}
		#endregion // ShowAtStartup accessor methods

		#region ShowAtStartup collection
        public ShowAtStartupCollection	MyShowAtStartups = new ShowAtStartupCollection( );

        public class ShowAtStartupCollection: IEnumerable
        {
            Type_ImageLayer parent;
            public Type_ImageLayer Parent
			{
				set
				{
                    this.SetSamplerState(0, SamplerStateparent = value;
				}
			}
			public ShowAtStartupEnumerator GetEnumerator() 
			{
				return new ShowAtStartupEnumerator(this.SetSamplerState(0, SamplerStateparent);
			}
		
			IEnumerator IEnumerable.SetSamplerState(0, SamplerStateGetEnumerator() 
			{
				return this.SetSamplerState(0, SamplerStateGetEnumerator();
			}
        }

        public class ShowAtStartupEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ImageLayer parent;
			public ShowAtStartupEnumerator(Type_ImageLayer par) 
			{
                this.SetSamplerState(0, SamplerStateparent = par;
                this.SetSamplerState(0, SamplerStatenIndex = -1;
			}
			public void Reset() 
			{
                this.SetSamplerState(0, SamplerStatenIndex = -1;
			}
			public bool MoveNext() 
			{
                this.SetSamplerState(0, SamplerStatenIndex++;
				return(this.SetSamplerState(0, SamplerStatenIndex < this.SetSamplerState(0, SamplerStateparent.SetSamplerState(0, SamplerStateShowAtStartupCount );
			}
			public SchemaBoolean  Current 
			{
				get 
				{
					return(this.SetSamplerState(0, SamplerStateparent.SetSamplerState(0, SamplerStateGetShowAtStartupAt(this.SetSamplerState(0, SamplerStatenIndex));
				}
			}
			object IEnumerator.SetSamplerState(0, SamplerStateCurrent 
			{
				get 
				{
					return(this.SetSamplerState(0, SamplerStateCurrent);
				}
			}
    	}

        #endregion // ShowAtStartup collection

		#region Name accessor methods
		public int GetNameMinCount()
		{
			return 1;
		}

		public int NameMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetNameMaxCount()
		{
			return 1;
		}

		public int NameMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetNameCount()
		{
			return this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "Name");
		}

		public int NameCount
		{
			get
			{
				return this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "Name");
			}
		}

		public bool HasName()
		{
			return this.SetSamplerState(0, SamplerStateHasDomChild(NodeType.SetSamplerState(0, SamplerStateElement, "", "Name");
		}

		public NameType GetNameAt(int index)
		{
			return new NameType(GetDomNodeValue(this.SetSamplerState(0, SamplerStateGetDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "Name", index)));
		}

		public XmlNode GetStartingNameCursor()
		{
			return this.SetSamplerState(0, SamplerStateGetDomFirstChild( NodeType.SetSamplerState(0, SamplerStateElement, "", "Name" );
		}

		public XmlNode GetAdvancedNameCursor( XmlNode curNode )
		{
			return this.SetSamplerState(0, SamplerStateGetDomNextChild( NodeType.SetSamplerState(0, SamplerStateElement, "", "Name", curNode );
		}

		public NameType GetNameValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.SetSamplerState(0, SamplerStateXml.SetSamplerState(0, SamplerStateXmlException("Out of range");
			else
				return new NameType( curNode.SetSamplerState(0, SamplerStateInnerText );
		}


		public NameType GetName()
		{
			return this.SetSamplerState(0, SamplerStateGetNameAt(0);
		}

		public NameType Name
		{
			get
			{
				return this.SetSamplerState(0, SamplerStateGetNameAt(0);
			}
		}

		public void RemoveNameAt(int index)
		{
            this.SetSamplerState(0, SamplerStateRemoveDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "Name", index);
		}

		public void RemoveName()
		{
			while (this.SetSamplerState(0, SamplerStateHasName()) this.SetSamplerState(0, SamplerStateRemoveNameAt(0);
		}

		public void AddName(NameType newValue)
		{
            this.SetSamplerState(0, SamplerStateAppendDomChild(NodeType.SetSamplerState(0, SamplerStateElement, "", "Name", newValue.SetSamplerState(0, SamplerStateToString());
		}

		public void InsertNameAt(NameType newValue, int index)
		{
            this.SetSamplerState(0, SamplerStateInsertDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "Name", index, newValue.SetSamplerState(0, SamplerStateToString());
		}

		public void ReplaceNameAt(NameType newValue, int index)
		{
            this.SetSamplerState(0, SamplerStateReplaceDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "Name", index, newValue.SetSamplerState(0, SamplerStateToString());
		}
		#endregion // Name accessor methods

		#region Name collection
        public NameCollection	MyNames = new NameCollection( );

        public class NameCollection: IEnumerable
        {
            Type_ImageLayer parent;
            public Type_ImageLayer Parent
			{
				set
				{
                    this.SetSamplerState(0, SamplerStateparent = value;
				}
			}
			public NameEnumerator GetEnumerator() 
			{
				return new NameEnumerator(this.SetSamplerState(0, SamplerStateparent);
			}
		
			IEnumerator IEnumerable.SetSamplerState(0, SamplerStateGetEnumerator() 
			{
				return this.SetSamplerState(0, SamplerStateGetEnumerator();
			}
        }

        public class NameEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ImageLayer parent;
			public NameEnumerator(Type_ImageLayer par) 
			{
                this.SetSamplerState(0, SamplerStateparent = par;
                this.SetSamplerState(0, SamplerStatenIndex = -1;
			}
			public void Reset() 
			{
                this.SetSamplerState(0, SamplerStatenIndex = -1;
			}
			public bool MoveNext() 
			{
                this.SetSamplerState(0, SamplerStatenIndex++;
				return(this.SetSamplerState(0, SamplerStatenIndex < this.SetSamplerState(0, SamplerStateparent.SetSamplerState(0, SamplerStateNameCount );
			}
			public NameType  Current 
			{
				get 
				{
					return(this.SetSamplerState(0, SamplerStateparent.SetSamplerState(0, SamplerStateGetNameAt(this.SetSamplerState(0, SamplerStatenIndex));
				}
			}
			object IEnumerator.SetSamplerState(0, SamplerStateCurrent 
			{
				get 
				{
					return(this.SetSamplerState(0, SamplerStateCurrent);
				}
			}
    	}

        #endregion // Name collection

		#region DistanceAboveSurface accessor methods
		public int GetDistanceAboveSurfaceMinCount()
		{
			return 1;
		}

		public int DistanceAboveSurfaceMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetDistanceAboveSurfaceMaxCount()
		{
			return 1;
		}

		public int DistanceAboveSurfaceMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetDistanceAboveSurfaceCount()
		{
			return this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "DistanceAboveSurface");
		}

		public int DistanceAboveSurfaceCount
		{
			get
			{
				return this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "DistanceAboveSurface");
			}
		}

		public bool HasDistanceAboveSurface()
		{
			return this.SetSamplerState(0, SamplerStateHasDomChild(NodeType.SetSamplerState(0, SamplerStateElement, "", "DistanceAboveSurface");
		}

		public SchemaDecimal GetDistanceAboveSurfaceAt(int index)
		{
			return new SchemaDecimal(GetDomNodeValue(this.SetSamplerState(0, SamplerStateGetDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "DistanceAboveSurface", index)));
		}

		public XmlNode GetStartingDistanceAboveSurfaceCursor()
		{
			return this.SetSamplerState(0, SamplerStateGetDomFirstChild( NodeType.SetSamplerState(0, SamplerStateElement, "", "DistanceAboveSurface" );
		}

		public XmlNode GetAdvancedDistanceAboveSurfaceCursor( XmlNode curNode )
		{
			return this.SetSamplerState(0, SamplerStateGetDomNextChild( NodeType.SetSamplerState(0, SamplerStateElement, "", "DistanceAboveSurface", curNode );
		}

		public SchemaDecimal GetDistanceAboveSurfaceValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.SetSamplerState(0, SamplerStateXml.SetSamplerState(0, SamplerStateXmlException("Out of range");
			else
				return new SchemaDecimal( curNode.SetSamplerState(0, SamplerStateInnerText );
		}


		public SchemaDecimal GetDistanceAboveSurface()
		{
			return this.SetSamplerState(0, SamplerStateGetDistanceAboveSurfaceAt(0);
		}

		public SchemaDecimal DistanceAboveSurface
		{
			get
			{
				return this.SetSamplerState(0, SamplerStateGetDistanceAboveSurfaceAt(0);
			}
		}

		public void RemoveDistanceAboveSurfaceAt(int index)
		{
            this.SetSamplerState(0, SamplerStateRemoveDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "DistanceAboveSurface", index);
		}

		public void RemoveDistanceAboveSurface()
		{
			while (this.SetSamplerState(0, SamplerStateHasDistanceAboveSurface()) this.SetSamplerState(0, SamplerStateRemoveDistanceAboveSurfaceAt(0);
		}

		public void AddDistanceAboveSurface(SchemaDecimal newValue)
		{
            this.SetSamplerState(0, SamplerStateAppendDomChild(NodeType.SetSamplerState(0, SamplerStateElement, "", "DistanceAboveSurface", newValue.SetSamplerState(0, SamplerStateToString());
		}

		public void InsertDistanceAboveSurfaceAt(SchemaDecimal newValue, int index)
		{
            this.SetSamplerState(0, SamplerStateInsertDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "DistanceAboveSurface", index, newValue.SetSamplerState(0, SamplerStateToString());
		}

		public void ReplaceDistanceAboveSurfaceAt(SchemaDecimal newValue, int index)
		{
            this.SetSamplerState(0, SamplerStateReplaceDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "DistanceAboveSurface", index, newValue.SetSamplerState(0, SamplerStateToString());
		}
		#endregion // DistanceAboveSurface accessor methods

		#region DistanceAboveSurface collection
        public DistanceAboveSurfaceCollection	MyDistanceAboveSurfaces = new DistanceAboveSurfaceCollection( );

        public class DistanceAboveSurfaceCollection: IEnumerable
        {
            Type_ImageLayer parent;
            public Type_ImageLayer Parent
			{
				set
				{
                    this.SetSamplerState(0, SamplerStateparent = value;
				}
			}
			public DistanceAboveSurfaceEnumerator GetEnumerator() 
			{
				return new DistanceAboveSurfaceEnumerator(this.SetSamplerState(0, SamplerStateparent);
			}
		
			IEnumerator IEnumerable.SetSamplerState(0, SamplerStateGetEnumerator() 
			{
				return this.SetSamplerState(0, SamplerStateGetEnumerator();
			}
        }

        public class DistanceAboveSurfaceEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ImageLayer parent;
			public DistanceAboveSurfaceEnumerator(Type_ImageLayer par) 
			{
                this.SetSamplerState(0, SamplerStateparent = par;
                this.SetSamplerState(0, SamplerStatenIndex = -1;
			}
			public void Reset() 
			{
                this.SetSamplerState(0, SamplerStatenIndex = -1;
			}
			public bool MoveNext() 
			{
                this.SetSamplerState(0, SamplerStatenIndex++;
				return(this.SetSamplerState(0, SamplerStatenIndex < this.SetSamplerState(0, SamplerStateparent.SetSamplerState(0, SamplerStateDistanceAboveSurfaceCount );
			}
			public SchemaDecimal  Current 
			{
				get 
				{
					return(this.SetSamplerState(0, SamplerStateparent.SetSamplerState(0, SamplerStateGetDistanceAboveSurfaceAt(this.SetSamplerState(0, SamplerStatenIndex));
				}
			}
			object IEnumerator.SetSamplerState(0, SamplerStateCurrent 
			{
				get 
				{
					return(this.SetSamplerState(0, SamplerStateCurrent);
				}
			}
    	}

        #endregion // DistanceAboveSurface collection

		#region BoundingBox accessor methods
		public int GetBoundingBoxMinCount()
		{
			return 1;
		}

		public int BoundingBoxMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetBoundingBoxMaxCount()
		{
			return 1;
		}

		public int BoundingBoxMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetBoundingBoxCount()
		{
			return this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "BoundingBox");
		}

		public int BoundingBoxCount
		{
			get
			{
				return this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "BoundingBox");
			}
		}

		public bool HasBoundingBox()
		{
			return this.SetSamplerState(0, SamplerStateHasDomChild(NodeType.SetSamplerState(0, SamplerStateElement, "", "BoundingBox");
		}

		public Type_LatLonBoundingBox2 GetBoundingBoxAt(int index)
		{
			return new Type_LatLonBoundingBox2(this.SetSamplerState(0, SamplerStateGetDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "BoundingBox", index));
		}

		public XmlNode GetStartingBoundingBoxCursor()
		{
			return this.SetSamplerState(0, SamplerStateGetDomFirstChild( NodeType.SetSamplerState(0, SamplerStateElement, "", "BoundingBox" );
		}

		public XmlNode GetAdvancedBoundingBoxCursor( XmlNode curNode )
		{
			return this.SetSamplerState(0, SamplerStateGetDomNextChild( NodeType.SetSamplerState(0, SamplerStateElement, "", "BoundingBox", curNode );
		}

		public Type_LatLonBoundingBox2 GetBoundingBoxValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.SetSamplerState(0, SamplerStateXml.SetSamplerState(0, SamplerStateXmlException("Out of range");
			else
				return new Type_LatLonBoundingBox2( curNode );
		}


		public Type_LatLonBoundingBox2 GetBoundingBox()
		{
			return this.SetSamplerState(0, SamplerStateGetBoundingBoxAt(0);
		}

		public Type_LatLonBoundingBox2 BoundingBox
		{
			get
			{
				return this.SetSamplerState(0, SamplerStateGetBoundingBoxAt(0);
			}
		}

		public void RemoveBoundingBoxAt(int index)
		{
            this.SetSamplerState(0, SamplerStateRemoveDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "BoundingBox", index);
		}

		public void RemoveBoundingBox()
		{
			while (this.SetSamplerState(0, SamplerStateHasBoundingBox()) this.SetSamplerState(0, SamplerStateRemoveBoundingBoxAt(0);
		}

		public void AddBoundingBox(Type_LatLonBoundingBox2 newValue)
		{
            this.SetSamplerState(0, SamplerStateAppendDomElement("", "BoundingBox", newValue);
		}

		public void InsertBoundingBoxAt(Type_LatLonBoundingBox2 newValue, int index)
		{
            this.SetSamplerState(0, SamplerStateInsertDomElementAt("", "BoundingBox", index, newValue);
		}

		public void ReplaceBoundingBoxAt(Type_LatLonBoundingBox2 newValue, int index)
		{
            this.SetSamplerState(0, SamplerStateReplaceDomElementAt("", "BoundingBox", index, newValue);
		}
		#endregion // BoundingBox accessor methods

		#region BoundingBox collection
        public BoundingBoxCollection	MyBoundingBoxs = new BoundingBoxCollection( );

        public class BoundingBoxCollection: IEnumerable
        {
            Type_ImageLayer parent;
            public Type_ImageLayer Parent
			{
				set
				{
                    this.SetSamplerState(0, SamplerStateparent = value;
				}
			}
			public BoundingBoxEnumerator GetEnumerator() 
			{
				return new BoundingBoxEnumerator(this.SetSamplerState(0, SamplerStateparent);
			}
		
			IEnumerator IEnumerable.SetSamplerState(0, SamplerStateGetEnumerator() 
			{
				return this.SetSamplerState(0, SamplerStateGetEnumerator();
			}
        }

        public class BoundingBoxEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ImageLayer parent;
			public BoundingBoxEnumerator(Type_ImageLayer par) 
			{
                this.SetSamplerState(0, SamplerStateparent = par;
                this.SetSamplerState(0, SamplerStatenIndex = -1;
			}
			public void Reset() 
			{
                this.SetSamplerState(0, SamplerStatenIndex = -1;
			}
			public bool MoveNext() 
			{
                this.SetSamplerState(0, SamplerStatenIndex++;
				return(this.SetSamplerState(0, SamplerStatenIndex < this.SetSamplerState(0, SamplerStateparent.SetSamplerState(0, SamplerStateBoundingBoxCount );
			}
			public Type_LatLonBoundingBox2  Current 
			{
				get 
				{
					return(this.SetSamplerState(0, SamplerStateparent.SetSamplerState(0, SamplerStateGetBoundingBoxAt(this.SetSamplerState(0, SamplerStatenIndex));
				}
			}
			object IEnumerator.SetSamplerState(0, SamplerStateCurrent 
			{
				get 
				{
					return(this.SetSamplerState(0, SamplerStateCurrent);
				}
			}
    	}

        #endregion // BoundingBox collection

		#region TexturePath accessor methods
		public int GetTexturePathMinCount()
		{
			return 1;
		}

		public int TexturePathMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetTexturePathMaxCount()
		{
			return 1;
		}

		public int TexturePathMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetTexturePathCount()
		{
			return this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "TexturePath");
		}

		public int TexturePathCount
		{
			get
			{
				return this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "TexturePath");
			}
		}

		public bool HasTexturePath()
		{
			return this.SetSamplerState(0, SamplerStateHasDomChild(NodeType.SetSamplerState(0, SamplerStateElement, "", "TexturePath");
		}

		public SchemaString GetTexturePathAt(int index)
		{
			return new SchemaString(GetDomNodeValue(this.SetSamplerState(0, SamplerStateGetDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "TexturePath", index)));
		}

		public XmlNode GetStartingTexturePathCursor()
		{
			return this.SetSamplerState(0, SamplerStateGetDomFirstChild( NodeType.SetSamplerState(0, SamplerStateElement, "", "TexturePath" );
		}

		public XmlNode GetAdvancedTexturePathCursor( XmlNode curNode )
		{
			return this.SetSamplerState(0, SamplerStateGetDomNextChild( NodeType.SetSamplerState(0, SamplerStateElement, "", "TexturePath", curNode );
		}

		public SchemaString GetTexturePathValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.SetSamplerState(0, SamplerStateXml.SetSamplerState(0, SamplerStateXmlException("Out of range");
			else
				return new SchemaString( curNode.SetSamplerState(0, SamplerStateInnerText );
		}


		public SchemaString GetTexturePath()
		{
			return this.SetSamplerState(0, SamplerStateGetTexturePathAt(0);
		}

		public SchemaString TexturePath
		{
			get
			{
				return this.SetSamplerState(0, SamplerStateGetTexturePathAt(0);
			}
		}

		public void RemoveTexturePathAt(int index)
		{
            this.SetSamplerState(0, SamplerStateRemoveDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "TexturePath", index);
		}

		public void RemoveTexturePath()
		{
			while (this.SetSamplerState(0, SamplerStateHasTexturePath()) this.SetSamplerState(0, SamplerStateRemoveTexturePathAt(0);
		}

		public void AddTexturePath(SchemaString newValue)
		{
            this.SetSamplerState(0, SamplerStateAppendDomChild(NodeType.SetSamplerState(0, SamplerStateElement, "", "TexturePath", newValue.SetSamplerState(0, SamplerStateToString());
		}

		public void InsertTexturePathAt(SchemaString newValue, int index)
		{
            this.SetSamplerState(0, SamplerStateInsertDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "TexturePath", index, newValue.SetSamplerState(0, SamplerStateToString());
		}

		public void ReplaceTexturePathAt(SchemaString newValue, int index)
		{
            this.SetSamplerState(0, SamplerStateReplaceDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "TexturePath", index, newValue.SetSamplerState(0, SamplerStateToString());
		}
		#endregion // TexturePath accessor methods

		#region TexturePath collection
        public TexturePathCollection	MyTexturePaths = new TexturePathCollection( );

        public class TexturePathCollection: IEnumerable
        {
            Type_ImageLayer parent;
            public Type_ImageLayer Parent
			{
				set
				{
                    this.SetSamplerState(0, SamplerStateparent = value;
				}
			}
			public TexturePathEnumerator GetEnumerator() 
			{
				return new TexturePathEnumerator(this.SetSamplerState(0, SamplerStateparent);
			}
		
			IEnumerator IEnumerable.SetSamplerState(0, SamplerStateGetEnumerator() 
			{
				return this.SetSamplerState(0, SamplerStateGetEnumerator();
			}
        }

        public class TexturePathEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ImageLayer parent;
			public TexturePathEnumerator(Type_ImageLayer par) 
			{
                this.SetSamplerState(0, SamplerStateparent = par;
                this.SetSamplerState(0, SamplerStatenIndex = -1;
			}
			public void Reset() 
			{
                this.SetSamplerState(0, SamplerStatenIndex = -1;
			}
			public bool MoveNext() 
			{
                this.SetSamplerState(0, SamplerStatenIndex++;
				return(this.SetSamplerState(0, SamplerStatenIndex < this.SetSamplerState(0, SamplerStateparent.SetSamplerState(0, SamplerStateTexturePathCount );
			}
			public SchemaString  Current 
			{
				get 
				{
					return(this.SetSamplerState(0, SamplerStateparent.SetSamplerState(0, SamplerStateGetTexturePathAt(this.SetSamplerState(0, SamplerStatenIndex));
				}
			}
			object IEnumerator.SetSamplerState(0, SamplerStateCurrent 
			{
				get 
				{
					return(this.SetSamplerState(0, SamplerStateCurrent);
				}
			}
    	}

        #endregion // TexturePath collection

		#region Opacity accessor methods
		public int GetOpacityMinCount()
		{
			return 1;
		}

		public int OpacityMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetOpacityMaxCount()
		{
			return 1;
		}

		public int OpacityMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetOpacityCount()
		{
			return this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "Opacity");
		}

		public int OpacityCount
		{
			get
			{
				return this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "Opacity");
			}
		}

		public bool HasOpacity()
		{
			return this.SetSamplerState(0, SamplerStateHasDomChild(NodeType.SetSamplerState(0, SamplerStateElement, "", "Opacity");
		}

		public OpacityType GetOpacityAt(int index)
		{
			return new OpacityType(GetDomNodeValue(this.SetSamplerState(0, SamplerStateGetDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "Opacity", index)));
		}

		public XmlNode GetStartingOpacityCursor()
		{
			return this.SetSamplerState(0, SamplerStateGetDomFirstChild( NodeType.SetSamplerState(0, SamplerStateElement, "", "Opacity" );
		}

		public XmlNode GetAdvancedOpacityCursor( XmlNode curNode )
		{
			return this.SetSamplerState(0, SamplerStateGetDomNextChild( NodeType.SetSamplerState(0, SamplerStateElement, "", "Opacity", curNode );
		}

		public OpacityType GetOpacityValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.SetSamplerState(0, SamplerStateXml.SetSamplerState(0, SamplerStateXmlException("Out of range");
			else
				return new OpacityType( curNode.SetSamplerState(0, SamplerStateInnerText );
		}


		public OpacityType GetOpacity()
		{
			return this.SetSamplerState(0, SamplerStateGetOpacityAt(0);
		}

		public OpacityType Opacity
		{
			get
			{
				return this.SetSamplerState(0, SamplerStateGetOpacityAt(0);
			}
		}

		public void RemoveOpacityAt(int index)
		{
            this.SetSamplerState(0, SamplerStateRemoveDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "Opacity", index);
		}

		public void RemoveOpacity()
		{
			while (this.SetSamplerState(0, SamplerStateHasOpacity()) this.SetSamplerState(0, SamplerStateRemoveOpacityAt(0);
		}

		public void AddOpacity(OpacityType newValue)
		{
            this.SetSamplerState(0, SamplerStateAppendDomChild(NodeType.SetSamplerState(0, SamplerStateElement, "", "Opacity", newValue.SetSamplerState(0, SamplerStateToString());
		}

		public void InsertOpacityAt(OpacityType newValue, int index)
		{
            this.SetSamplerState(0, SamplerStateInsertDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "Opacity", index, newValue.SetSamplerState(0, SamplerStateToString());
		}

		public void ReplaceOpacityAt(OpacityType newValue, int index)
		{
            this.SetSamplerState(0, SamplerStateReplaceDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "Opacity", index, newValue.SetSamplerState(0, SamplerStateToString());
		}
		#endregion // Opacity accessor methods

		#region Opacity collection
        public OpacityCollection	MyOpacitys = new OpacityCollection( );

        public class OpacityCollection: IEnumerable
        {
            Type_ImageLayer parent;
            public Type_ImageLayer Parent
			{
				set
				{
                    this.SetSamplerState(0, SamplerStateparent = value;
				}
			}
			public OpacityEnumerator GetEnumerator() 
			{
				return new OpacityEnumerator(this.SetSamplerState(0, SamplerStateparent);
			}
		
			IEnumerator IEnumerable.SetSamplerState(0, SamplerStateGetEnumerator() 
			{
				return this.SetSamplerState(0, SamplerStateGetEnumerator();
			}
        }

        public class OpacityEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ImageLayer parent;
			public OpacityEnumerator(Type_ImageLayer par) 
			{
                this.SetSamplerState(0, SamplerStateparent = par;
                this.SetSamplerState(0, SamplerStatenIndex = -1;
			}
			public void Reset() 
			{
                this.SetSamplerState(0, SamplerStatenIndex = -1;
			}
			public bool MoveNext() 
			{
                this.SetSamplerState(0, SamplerStatenIndex++;
				return(this.SetSamplerState(0, SamplerStatenIndex < this.SetSamplerState(0, SamplerStateparent.SetSamplerState(0, SamplerStateOpacityCount );
			}
			public OpacityType  Current 
			{
				get 
				{
					return(this.SetSamplerState(0, SamplerStateparent.SetSamplerState(0, SamplerStateGetOpacityAt(this.SetSamplerState(0, SamplerStatenIndex));
				}
			}
			object IEnumerator.SetSamplerState(0, SamplerStateCurrent 
			{
				get 
				{
					return(this.SetSamplerState(0, SamplerStateCurrent);
				}
			}
    	}

        #endregion // Opacity collection

		#region TerrainMapped accessor methods
		public int GetTerrainMappedMinCount()
		{
			return 1;
		}

		public int TerrainMappedMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetTerrainMappedMaxCount()
		{
			return 1;
		}

		public int TerrainMappedMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetTerrainMappedCount()
		{
			return this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "TerrainMapped");
		}

		public int TerrainMappedCount
		{
			get
			{
				return this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "TerrainMapped");
			}
		}

		public bool HasTerrainMapped()
		{
			return this.SetSamplerState(0, SamplerStateHasDomChild(NodeType.SetSamplerState(0, SamplerStateElement, "", "TerrainMapped");
		}

		public SchemaBoolean GetTerrainMappedAt(int index)
		{
			return new SchemaBoolean(GetDomNodeValue(this.SetSamplerState(0, SamplerStateGetDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "TerrainMapped", index)));
		}

		public XmlNode GetStartingTerrainMappedCursor()
		{
			return this.SetSamplerState(0, SamplerStateGetDomFirstChild( NodeType.SetSamplerState(0, SamplerStateElement, "", "TerrainMapped" );
		}

		public XmlNode GetAdvancedTerrainMappedCursor( XmlNode curNode )
		{
			return this.SetSamplerState(0, SamplerStateGetDomNextChild( NodeType.SetSamplerState(0, SamplerStateElement, "", "TerrainMapped", curNode );
		}

		public SchemaBoolean GetTerrainMappedValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.SetSamplerState(0, SamplerStateXml.SetSamplerState(0, SamplerStateXmlException("Out of range");
			else
				return new SchemaBoolean( curNode.SetSamplerState(0, SamplerStateInnerText );
		}


		public SchemaBoolean GetTerrainMapped()
		{
			return this.SetSamplerState(0, SamplerStateGetTerrainMappedAt(0);
		}

		public SchemaBoolean TerrainMapped
		{
			get
			{
				return this.SetSamplerState(0, SamplerStateGetTerrainMappedAt(0);
			}
		}

		public void RemoveTerrainMappedAt(int index)
		{
            this.SetSamplerState(0, SamplerStateRemoveDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "TerrainMapped", index);
		}

		public void RemoveTerrainMapped()
		{
			while (this.SetSamplerState(0, SamplerStateHasTerrainMapped()) this.SetSamplerState(0, SamplerStateRemoveTerrainMappedAt(0);
		}

		public void AddTerrainMapped(SchemaBoolean newValue)
		{
            this.SetSamplerState(0, SamplerStateAppendDomChild(NodeType.SetSamplerState(0, SamplerStateElement, "", "TerrainMapped", newValue.SetSamplerState(0, SamplerStateToString());
		}

		public void InsertTerrainMappedAt(SchemaBoolean newValue, int index)
		{
            this.SetSamplerState(0, SamplerStateInsertDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "TerrainMapped", index, newValue.SetSamplerState(0, SamplerStateToString());
		}

		public void ReplaceTerrainMappedAt(SchemaBoolean newValue, int index)
		{
            this.SetSamplerState(0, SamplerStateReplaceDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "TerrainMapped", index, newValue.SetSamplerState(0, SamplerStateToString());
		}
		#endregion // TerrainMapped accessor methods

		#region TerrainMapped collection
        public TerrainMappedCollection	MyTerrainMappeds = new TerrainMappedCollection( );

        public class TerrainMappedCollection: IEnumerable
        {
            Type_ImageLayer parent;
            public Type_ImageLayer Parent
			{
				set
				{
                    this.SetSamplerState(0, SamplerStateparent = value;
				}
			}
			public TerrainMappedEnumerator GetEnumerator() 
			{
				return new TerrainMappedEnumerator(this.SetSamplerState(0, SamplerStateparent);
			}
		
			IEnumerator IEnumerable.SetSamplerState(0, SamplerStateGetEnumerator() 
			{
				return this.SetSamplerState(0, SamplerStateGetEnumerator();
			}
        }

        public class TerrainMappedEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ImageLayer parent;
			public TerrainMappedEnumerator(Type_ImageLayer par) 
			{
                this.SetSamplerState(0, SamplerStateparent = par;
                this.SetSamplerState(0, SamplerStatenIndex = -1;
			}
			public void Reset() 
			{
                this.SetSamplerState(0, SamplerStatenIndex = -1;
			}
			public bool MoveNext() 
			{
                this.SetSamplerState(0, SamplerStatenIndex++;
				return(this.SetSamplerState(0, SamplerStatenIndex < this.SetSamplerState(0, SamplerStateparent.SetSamplerState(0, SamplerStateTerrainMappedCount );
			}
			public SchemaBoolean  Current 
			{
				get 
				{
					return(this.SetSamplerState(0, SamplerStateparent.SetSamplerState(0, SamplerStateGetTerrainMappedAt(this.SetSamplerState(0, SamplerStatenIndex));
				}
			}
			object IEnumerator.SetSamplerState(0, SamplerStateCurrent 
			{
				get 
				{
					return(this.SetSamplerState(0, SamplerStateCurrent);
				}
			}
    	}

        #endregion // TerrainMapped collection

		#region TransparencyColor accessor methods
		public int GetTransparencyColorMinCount()
		{
			return 0;
		}

		public int TransparencyColorMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetTransparencyColorMaxCount()
		{
			return 1;
		}

		public int TransparencyColorMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetTransparencyColorCount()
		{
			return this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "TransparencyColor");
		}

		public int TransparencyColorCount
		{
			get
			{
				return this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "TransparencyColor");
			}
		}

		public bool HasTransparencyColor()
		{
			return this.SetSamplerState(0, SamplerStateHasDomChild(NodeType.SetSamplerState(0, SamplerStateElement, "", "TransparencyColor");
		}

		public Type_RGBColor2 GetTransparencyColorAt(int index)
		{
			return new Type_RGBColor2(this.SetSamplerState(0, SamplerStateGetDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "TransparencyColor", index));
		}

		public XmlNode GetStartingTransparencyColorCursor()
		{
			return this.SetSamplerState(0, SamplerStateGetDomFirstChild( NodeType.SetSamplerState(0, SamplerStateElement, "", "TransparencyColor" );
		}

		public XmlNode GetAdvancedTransparencyColorCursor( XmlNode curNode )
		{
			return this.SetSamplerState(0, SamplerStateGetDomNextChild( NodeType.SetSamplerState(0, SamplerStateElement, "", "TransparencyColor", curNode );
		}

		public Type_RGBColor2 GetTransparencyColorValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.SetSamplerState(0, SamplerStateXml.SetSamplerState(0, SamplerStateXmlException("Out of range");
			else
				return new Type_RGBColor2( curNode );
		}


		public Type_RGBColor2 GetTransparencyColor()
		{
			return this.SetSamplerState(0, SamplerStateGetTransparencyColorAt(0);
		}

		public Type_RGBColor2 TransparencyColor
		{
			get
			{
				return this.SetSamplerState(0, SamplerStateGetTransparencyColorAt(0);
			}
		}

		public void RemoveTransparencyColorAt(int index)
		{
            this.SetSamplerState(0, SamplerStateRemoveDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "TransparencyColor", index);
		}

		public void RemoveTransparencyColor()
		{
			while (this.SetSamplerState(0, SamplerStateHasTransparencyColor()) this.SetSamplerState(0, SamplerStateRemoveTransparencyColorAt(0);
		}

		public void AddTransparencyColor(Type_RGBColor2 newValue)
		{
            this.SetSamplerState(0, SamplerStateAppendDomElement("", "TransparencyColor", newValue);
		}

		public void InsertTransparencyColorAt(Type_RGBColor2 newValue, int index)
		{
            this.SetSamplerState(0, SamplerStateInsertDomElementAt("", "TransparencyColor", index, newValue);
		}

		public void ReplaceTransparencyColorAt(Type_RGBColor2 newValue, int index)
		{
            this.SetSamplerState(0, SamplerStateReplaceDomElementAt("", "TransparencyColor", index, newValue);
		}
		#endregion // TransparencyColor accessor methods

		#region TransparencyColor collection
        public TransparencyColorCollection	MyTransparencyColors = new TransparencyColorCollection( );

        public class TransparencyColorCollection: IEnumerable
        {
            Type_ImageLayer parent;
            public Type_ImageLayer Parent
			{
				set
				{
                    this.SetSamplerState(0, SamplerStateparent = value;
				}
			}
			public TransparencyColorEnumerator GetEnumerator() 
			{
				return new TransparencyColorEnumerator(this.SetSamplerState(0, SamplerStateparent);
			}
		
			IEnumerator IEnumerable.SetSamplerState(0, SamplerStateGetEnumerator() 
			{
				return this.SetSamplerState(0, SamplerStateGetEnumerator();
			}
        }

        public class TransparencyColorEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ImageLayer parent;
			public TransparencyColorEnumerator(Type_ImageLayer par) 
			{
                this.SetSamplerState(0, SamplerStateparent = par;
                this.SetSamplerState(0, SamplerStatenIndex = -1;
			}
			public void Reset() 
			{
                this.SetSamplerState(0, SamplerStatenIndex = -1;
			}
			public bool MoveNext() 
			{
                this.SetSamplerState(0, SamplerStatenIndex++;
				return(this.SetSamplerState(0, SamplerStatenIndex < this.SetSamplerState(0, SamplerStateparent.SetSamplerState(0, SamplerStateTransparencyColorCount );
			}
			public Type_RGBColor2  Current 
			{
				get 
				{
					return(this.SetSamplerState(0, SamplerStateparent.SetSamplerState(0, SamplerStateGetTransparencyColorAt(this.SetSamplerState(0, SamplerStatenIndex));
				}
			}
			object IEnumerator.SetSamplerState(0, SamplerStateCurrent 
			{
				get 
				{
					return(this.SetSamplerState(0, SamplerStateCurrent);
				}
			}
    	}

        #endregion // TransparencyColor collection

		#region LegendImagePath accessor methods
		public int GetLegendImagePathMinCount()
		{
			return 0;
		}

		public int LegendImagePathMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetLegendImagePathMaxCount()
		{
			return 1;
		}

		public int LegendImagePathMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetLegendImagePathCount()
		{
			return this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "LegendImagePath");
		}

		public int LegendImagePathCount
		{
			get
			{
				return this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "LegendImagePath");
			}
		}

		public bool HasLegendImagePath()
		{
			return this.SetSamplerState(0, SamplerStateHasDomChild(NodeType.SetSamplerState(0, SamplerStateElement, "", "LegendImagePath");
		}

		public SchemaString GetLegendImagePathAt(int index)
		{
			return new SchemaString(GetDomNodeValue(this.SetSamplerState(0, SamplerStateGetDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "LegendImagePath", index)));
		}

		public XmlNode GetStartingLegendImagePathCursor()
		{
			return this.SetSamplerState(0, SamplerStateGetDomFirstChild( NodeType.SetSamplerState(0, SamplerStateElement, "", "LegendImagePath" );
		}

		public XmlNode GetAdvancedLegendImagePathCursor( XmlNode curNode )
		{
			return this.SetSamplerState(0, SamplerStateGetDomNextChild( NodeType.SetSamplerState(0, SamplerStateElement, "", "LegendImagePath", curNode );
		}

		public SchemaString GetLegendImagePathValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.SetSamplerState(0, SamplerStateXml.SetSamplerState(0, SamplerStateXmlException("Out of range");
			else
				return new SchemaString( curNode.SetSamplerState(0, SamplerStateInnerText );
		}


		public SchemaString GetLegendImagePath()
		{
			return this.SetSamplerState(0, SamplerStateGetLegendImagePathAt(0);
		}

		public SchemaString LegendImagePath
		{
			get
			{
				return this.SetSamplerState(0, SamplerStateGetLegendImagePathAt(0);
			}
		}

		public void RemoveLegendImagePathAt(int index)
		{
            this.SetSamplerState(0, SamplerStateRemoveDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "LegendImagePath", index);
		}

		public void RemoveLegendImagePath()
		{
			while (this.SetSamplerState(0, SamplerStateHasLegendImagePath()) this.SetSamplerState(0, SamplerStateRemoveLegendImagePathAt(0);
		}

		public void AddLegendImagePath(SchemaString newValue)
		{
            this.SetSamplerState(0, SamplerStateAppendDomChild(NodeType.SetSamplerState(0, SamplerStateElement, "", "LegendImagePath", newValue.SetSamplerState(0, SamplerStateToString());
		}

		public void InsertLegendImagePathAt(SchemaString newValue, int index)
		{
            this.SetSamplerState(0, SamplerStateInsertDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "LegendImagePath", index, newValue.SetSamplerState(0, SamplerStateToString());
		}

		public void ReplaceLegendImagePathAt(SchemaString newValue, int index)
		{
            this.SetSamplerState(0, SamplerStateReplaceDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "LegendImagePath", index, newValue.SetSamplerState(0, SamplerStateToString());
		}
		#endregion // LegendImagePath accessor methods

		#region LegendImagePath collection
        public LegendImagePathCollection	MyLegendImagePaths = new LegendImagePathCollection( );

        public class LegendImagePathCollection: IEnumerable
        {
            Type_ImageLayer parent;
            public Type_ImageLayer Parent
			{
				set
				{
                    this.SetSamplerState(0, SamplerStateparent = value;
				}
			}
			public LegendImagePathEnumerator GetEnumerator() 
			{
				return new LegendImagePathEnumerator(this.SetSamplerState(0, SamplerStateparent);
			}
		
			IEnumerator IEnumerable.SetSamplerState(0, SamplerStateGetEnumerator() 
			{
				return this.SetSamplerState(0, SamplerStateGetEnumerator();
			}
        }

        public class LegendImagePathEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ImageLayer parent;
			public LegendImagePathEnumerator(Type_ImageLayer par) 
			{
                this.SetSamplerState(0, SamplerStateparent = par;
                this.SetSamplerState(0, SamplerStatenIndex = -1;
			}
			public void Reset() 
			{
                this.SetSamplerState(0, SamplerStatenIndex = -1;
			}
			public bool MoveNext() 
			{
                this.SetSamplerState(0, SamplerStatenIndex++;
				return(this.SetSamplerState(0, SamplerStatenIndex < this.SetSamplerState(0, SamplerStateparent.SetSamplerState(0, SamplerStateLegendImagePathCount );
			}
			public SchemaString  Current 
			{
				get 
				{
					return(this.SetSamplerState(0, SamplerStateparent.SetSamplerState(0, SamplerStateGetLegendImagePathAt(this.SetSamplerState(0, SamplerStatenIndex));
				}
			}
			object IEnumerator.SetSamplerState(0, SamplerStateCurrent 
			{
				get 
				{
					return(this.SetSamplerState(0, SamplerStateCurrent);
				}
			}
    	}

        #endregion // LegendImagePath collection

		#region ExtendedInformation accessor methods
		public int GetExtendedInformationMinCount()
		{
			return 0;
		}

		public int ExtendedInformationMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetExtendedInformationMaxCount()
		{
			return 1;
		}

		public int ExtendedInformationMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetExtendedInformationCount()
		{
			return this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "ExtendedInformation");
		}

		public int ExtendedInformationCount
		{
			get
			{
				return this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "ExtendedInformation");
			}
		}

		public bool HasExtendedInformation()
		{
			return this.SetSamplerState(0, SamplerStateHasDomChild(NodeType.SetSamplerState(0, SamplerStateElement, "", "ExtendedInformation");
		}

		public Type_ExtendedInformation GetExtendedInformationAt(int index)
		{
			return new Type_ExtendedInformation(this.SetSamplerState(0, SamplerStateGetDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "ExtendedInformation", index));
		}

		public XmlNode GetStartingExtendedInformationCursor()
		{
			return this.SetSamplerState(0, SamplerStateGetDomFirstChild( NodeType.SetSamplerState(0, SamplerStateElement, "", "ExtendedInformation" );
		}

		public XmlNode GetAdvancedExtendedInformationCursor( XmlNode curNode )
		{
			return this.SetSamplerState(0, SamplerStateGetDomNextChild( NodeType.SetSamplerState(0, SamplerStateElement, "", "ExtendedInformation", curNode );
		}

		public Type_ExtendedInformation GetExtendedInformationValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.SetSamplerState(0, SamplerStateXml.SetSamplerState(0, SamplerStateXmlException("Out of range");
			else
				return new Type_ExtendedInformation( curNode );
		}


		public Type_ExtendedInformation GetExtendedInformation()
		{
			return this.SetSamplerState(0, SamplerStateGetExtendedInformationAt(0);
		}

		public Type_ExtendedInformation ExtendedInformation
		{
			get
			{
				return this.SetSamplerState(0, SamplerStateGetExtendedInformationAt(0);
			}
		}

		public void RemoveExtendedInformationAt(int index)
		{
            this.SetSamplerState(0, SamplerStateRemoveDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "ExtendedInformation", index);
		}

		public void RemoveExtendedInformation()
		{
			while (this.SetSamplerState(0, SamplerStateHasExtendedInformation()) this.SetSamplerState(0, SamplerStateRemoveExtendedInformationAt(0);
		}

		public void AddExtendedInformation(Type_ExtendedInformation newValue)
		{
            this.SetSamplerState(0, SamplerStateAppendDomElement("", "ExtendedInformation", newValue);
		}

		public void InsertExtendedInformationAt(Type_ExtendedInformation newValue, int index)
		{
            this.SetSamplerState(0, SamplerStateInsertDomElementAt("", "ExtendedInformation", index, newValue);
		}

		public void ReplaceExtendedInformationAt(Type_ExtendedInformation newValue, int index)
		{
            this.SetSamplerState(0, SamplerStateReplaceDomElementAt("", "ExtendedInformation", index, newValue);
		}
		#endregion // ExtendedInformation accessor methods

		#region ExtendedInformation collection
        public ExtendedInformationCollection	MyExtendedInformations = new ExtendedInformationCollection( );

        public class ExtendedInformationCollection: IEnumerable
        {
            Type_ImageLayer parent;
            public Type_ImageLayer Parent
			{
				set
				{
                    this.SetSamplerState(0, SamplerStateparent = value;
				}
			}
			public ExtendedInformationEnumerator GetEnumerator() 
			{
				return new ExtendedInformationEnumerator(this.SetSamplerState(0, SamplerStateparent);
			}
		
			IEnumerator IEnumerable.SetSamplerState(0, SamplerStateGetEnumerator() 
			{
				return this.SetSamplerState(0, SamplerStateGetEnumerator();
			}
        }

        public class ExtendedInformationEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ImageLayer parent;
			public ExtendedInformationEnumerator(Type_ImageLayer par) 
			{
                this.SetSamplerState(0, SamplerStateparent = par;
                this.SetSamplerState(0, SamplerStatenIndex = -1;
			}
			public void Reset() 
			{
                this.SetSamplerState(0, SamplerStatenIndex = -1;
			}
			public bool MoveNext() 
			{
                this.SetSamplerState(0, SamplerStatenIndex++;
				return(this.SetSamplerState(0, SamplerStatenIndex < this.SetSamplerState(0, SamplerStateparent.SetSamplerState(0, SamplerStateExtendedInformationCount );
			}
			public Type_ExtendedInformation  Current 
			{
				get 
				{
					return(this.SetSamplerState(0, SamplerStateparent.SetSamplerState(0, SamplerStateGetExtendedInformationAt(this.SetSamplerState(0, SamplerStatenIndex));
				}
			}
			object IEnumerator.SetSamplerState(0, SamplerStateCurrent 
			{
				get 
				{
					return(this.SetSamplerState(0, SamplerStateCurrent);
				}
			}
    	}

        #endregion // ExtendedInformation collection

		#region TransparentColor accessor methods
		public int GetTransparentColorMinCount()
		{
			return 0;
		}

		public int TransparentColorMinCount
		{
			get
			{
				return 0;
			}
		}

		public int GetTransparentColorMaxCount()
		{
			return 1;
		}

		public int TransparentColorMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetTransparentColorCount()
		{
			return this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "TransparentColor");
		}

		public int TransparentColorCount
		{
			get
			{
				return this.SetSamplerState(0, SamplerStateDomChildCount(NodeType.SetSamplerState(0, SamplerStateElement, "", "TransparentColor");
			}
		}

		public bool HasTransparentColor()
		{
			return this.SetSamplerState(0, SamplerStateHasDomChild(NodeType.SetSamplerState(0, SamplerStateElement, "", "TransparentColor");
		}

		public Type_RGBColor2 GetTransparentColorAt(int index)
		{
			return new Type_RGBColor2(this.SetSamplerState(0, SamplerStateGetDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "TransparentColor", index));
		}

		public XmlNode GetStartingTransparentColorCursor()
		{
			return this.SetSamplerState(0, SamplerStateGetDomFirstChild( NodeType.SetSamplerState(0, SamplerStateElement, "", "TransparentColor" );
		}

		public XmlNode GetAdvancedTransparentColorCursor( XmlNode curNode )
		{
			return this.SetSamplerState(0, SamplerStateGetDomNextChild( NodeType.SetSamplerState(0, SamplerStateElement, "", "TransparentColor", curNode );
		}

		public Type_RGBColor2 GetTransparentColorValueAtCursor( XmlNode curNode )
		{
			if( curNode == null )
				  throw new Altova.SetSamplerState(0, SamplerStateXml.SetSamplerState(0, SamplerStateXmlException("Out of range");
			else
				return new Type_RGBColor2( curNode );
		}


		public Type_RGBColor2 GetTransparentColor()
		{
			return this.SetSamplerState(0, SamplerStateGetTransparentColorAt(0);
		}

		public Type_RGBColor2 TransparentColor
		{
			get
			{
				return this.SetSamplerState(0, SamplerStateGetTransparentColorAt(0);
			}
		}

		public void RemoveTransparentColorAt(int index)
		{
            this.SetSamplerState(0, SamplerStateRemoveDomChildAt(NodeType.SetSamplerState(0, SamplerStateElement, "", "TransparentColor", index);
		}

		public void RemoveTransparentColor()
		{
			while (this.SetSamplerState(0, SamplerStateHasTransparentColor()) this.SetSamplerState(0, SamplerStateRemoveTransparentColorAt(0);
		}

		public void AddTransparentColor(Type_RGBColor2 newValue)
		{
            this.SetSamplerState(0, SamplerStateAppendDomElement("", "TransparentColor", newValue);
		}

		public void InsertTransparentColorAt(Type_RGBColor2 newValue, int index)
		{
            this.SetSamplerState(0, SamplerStateInsertDomElementAt("", "TransparentColor", index, newValue);
		}

		public void ReplaceTransparentColorAt(Type_RGBColor2 newValue, int index)
		{
            this.SetSamplerState(0, SamplerStateReplaceDomElementAt("", "TransparentColor", index, newValue);
		}
		#endregion // TransparentColor accessor methods

		#region TransparentColor collection
        public TransparentColorCollection	MyTransparentColors = new TransparentColorCollection( );

        public class TransparentColorCollection: IEnumerable
        {
            Type_ImageLayer parent;
            public Type_ImageLayer Parent
			{
				set
				{
                    this.SetSamplerState(0, SamplerStateparent = value;
				}
			}
			public TransparentColorEnumerator GetEnumerator() 
			{
				return new TransparentColorEnumerator(this.SetSamplerState(0, SamplerStateparent);
			}
		
			IEnumerator IEnumerable.SetSamplerState(0, SamplerStateGetEnumerator() 
			{
				return this.SetSamplerState(0, SamplerStateGetEnumerator();
			}
        }

        public class TransparentColorEnumerator: IEnumerator 
        {
			int nIndex;
			Type_ImageLayer parent;
			public TransparentColorEnumerator(Type_ImageLayer par) 
			{
                this.SetSamplerState(0, SamplerStateparent = par;
                this.SetSamplerState(0, SamplerStatenIndex = -1;
			}
			public void Reset() 
			{
                this.SetSamplerState(0, SamplerStatenIndex = -1;
			}
			public bool MoveNext() 
			{
                this.SetSamplerState(0, SamplerStatenIndex++;
				return(this.SetSamplerState(0, SamplerStatenIndex < this.SetSamplerState(0, SamplerStateparent.SetSamplerState(0, SamplerStateTransparentColorCount );
			}
			public Type_RGBColor2  Current 
			{
				get 
				{
					return(this.SetSamplerState(0, SamplerStateparent.SetSamplerState(0, SamplerStateGetTransparentColorAt(this.SetSamplerState(0, SamplerStatenIndex));
				}
			}
			object IEnumerator.SetSamplerState(0, SamplerStateCurrent 
			{
				get 
				{
					return(this.SetSamplerState(0, SamplerStateCurrent);
				}
			}
    	}

        #endregion // TransparentColor collection

        private void SetCollectionParents()
        {
            this.SetSamplerState(0, SamplerStateMyShowAtStartups.SetSamplerState(0, SamplerStateParent = this;
            this.SetSamplerState(0, SamplerStateMyNames.SetSamplerState(0, SamplerStateParent = this;
            this.SetSamplerState(0, SamplerStateMyDistanceAboveSurfaces.SetSamplerState(0, SamplerStateParent = this;
            this.SetSamplerState(0, SamplerStateMyBoundingBoxs.SetSamplerState(0, SamplerStateParent = this;
            this.SetSamplerState(0, SamplerStateMyTexturePaths.SetSamplerState(0, SamplerStateParent = this;
            this.SetSamplerState(0, SamplerStateMyOpacitys.SetSamplerState(0, SamplerStateParent = this;
            this.SetSamplerState(0, SamplerStateMyTerrainMappeds.SetSamplerState(0, SamplerStateParent = this;
            this.SetSamplerState(0, SamplerStateMyTransparencyColors.SetSamplerState(0, SamplerStateParent = this;
            this.SetSamplerState(0, SamplerStateMyLegendImagePaths.SetSamplerState(0, SamplerStateParent = this;
            this.SetSamplerState(0, SamplerStateMyExtendedInformations.SetSamplerState(0, SamplerStateParent = this;
            this.SetSamplerState(0, SamplerStateMyTransparentColors.SetSamplerState(0, SamplerStateParent = this; 
	}
}
}
